export const ATTENDANCE_REPORT_START = 'ATTENDANCE_REPORT_START'
export const ATTENDANCE_REPORT_SUCCESS = 'ATTENDANCE_REPORT_SUCCESS'
export const ATTENDANCE_REPORT_FAIL = 'ATTENDANCE_REPORT_FAIL'

export const EFFORT_REPORT_START = 'EFFORT_REPORT_START'
export const EFFORT_REPORT_SUCCESS = 'EFFORT_REPORT_SUCCESS'
export const EFFORT_REPORT_FAIL = 'EFFORT_REPORT_FAIL'
