export const SEARCH_EXPENSE_START_ACTION = 'SEARCH_EXPENSE_START_ACTION'
export const SEARCH_EXPENSE_SUCCESS_ACTION = 'SEARCH_EXPENSE_SUCCESS_ACTION'
export const SEARCH_EXPENSE_FAIL_ACTION = 'SEARCH_EXPENSE_FAIL_ACTION'

export const CHANGE_LOCATION_TYPE = 'CHANGE_LOCATION_TYPE'
