/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.tables.records.Ap1Record

import java.time.OffsetDateTime
import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row12
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class Ap1(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Ap1Record>?,
    aliased: Table<Ap1Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Ap1Record>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.ap1</code>
         */
        val AP1: Ap1 = Ap1()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Ap1Record> = Ap1Record::class.java

    /**
     * The column <code>public.ap1.id</code>.
     */
    val ID: TableField<Ap1Record, String?> = createField(DSL.name("id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.ap1.updated_by</code>.
     */
    val UPDATED_BY: TableField<Ap1Record, String?> = createField(DSL.name("updated_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.ap1.group_id</code>.
     */
    val GROUP_ID: TableField<Ap1Record, String?> = createField(DSL.name("group_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.ap1.cmdoc_id</code>.
     */
    val CMDOC_ID: TableField<Ap1Record, String?> = createField(DSL.name("cmdoc_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.ap1.approver_id</code>.
     */
    val APPROVER_ID: TableField<Ap1Record, String?> = createField(DSL.name("approver_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.ap1.created_by</code>.
     */
    val CREATED_BY: TableField<Ap1Record, String?> = createField(DSL.name("created_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.ap1.is_current</code>.
     */
    val IS_CURRENT: TableField<Ap1Record, Boolean?> = createField(DSL.name("is_current"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column <code>public.ap1.updated_on</code>.
     */
    val UPDATED_ON: TableField<Ap1Record, OffsetDateTime?> = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.ap1.created_on</code>.
     */
    val CREATED_ON: TableField<Ap1Record, OffsetDateTime?> = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.ap1.action</code>.
     */
    val ACTION: TableField<Ap1Record, String?> = createField(DSL.name("action"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.ap1.stale_id</code>.
     */
    val STALE_ID: TableField<Ap1Record, String?> = createField(DSL.name("stale_id"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.ap1.comment</code>.
     */
    val COMMENT: TableField<Ap1Record, String?> = createField(DSL.name("comment"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<Ap1Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Ap1Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.ap1</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.ap1</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.ap1</code> table reference
     */
    constructor(): this(DSL.name("ap1"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Ap1Record>): this(Internal.createPathAlias(child, key), child, key, AP1, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): Ap1 = Ap1(DSL.name(alias), this)
    override fun `as`(alias: Name): Ap1 = Ap1(alias, this)
    override fun `as`(alias: Table<*>): Ap1 = Ap1(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Ap1 = Ap1(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Ap1 = Ap1(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Ap1 = Ap1(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row12<String?, String?, String?, String?, String?, String?, Boolean?, OffsetDateTime?, OffsetDateTime?, String?, String?, String?> = super.fieldsRow() as Row12<String?, String?, String?, String?, String?, String?, Boolean?, OffsetDateTime?, OffsetDateTime?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?, String?, Boolean?, OffsetDateTime?, OffsetDateTime?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?, String?, Boolean?, OffsetDateTime?, OffsetDateTime?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
