/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.keys.BATCH_JOB_EXECUTION_PKEY
import com.squer.prorpel.jooq.keys.BATCH_JOB_EXECUTION__JOB_INST_EXEC_FK
import com.squer.prorpel.jooq.tables.records.BatchJobExecutionRecord

import java.time.LocalDateTime
import java.util.function.Function

import javax.annotation.processing.Generated

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row11
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class BatchJobExecution(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, BatchJobExecutionRecord>?,
    aliased: Table<BatchJobExecutionRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<BatchJobExecutionRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.batch_job_execution</code>
         */
        val BATCH_JOB_EXECUTION: BatchJobExecution = BatchJobExecution()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BatchJobExecutionRecord> = BatchJobExecutionRecord::class.java

    /**
     * The column <code>public.batch_job_execution.job_execution_id</code>.
     */
    val JOB_EXECUTION_ID: TableField<BatchJobExecutionRecord, Long?> = createField(DSL.name("job_execution_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.batch_job_execution.version</code>.
     */
    val VERSION: TableField<BatchJobExecutionRecord, Long?> = createField(DSL.name("version"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.batch_job_execution.job_instance_id</code>.
     */
    val JOB_INSTANCE_ID: TableField<BatchJobExecutionRecord, Long?> = createField(DSL.name("job_instance_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.batch_job_execution.create_time</code>.
     */
    val CREATE_TIME: TableField<BatchJobExecutionRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.batch_job_execution.start_time</code>.
     */
    val START_TIME: TableField<BatchJobExecutionRecord, LocalDateTime?> = createField(DSL.name("start_time"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.batch_job_execution.end_time</code>.
     */
    val END_TIME: TableField<BatchJobExecutionRecord, LocalDateTime?> = createField(DSL.name("end_time"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.batch_job_execution.status</code>.
     */
    val STATUS: TableField<BatchJobExecutionRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(10), this, "")

    /**
     * The column <code>public.batch_job_execution.exit_code</code>.
     */
    val EXIT_CODE: TableField<BatchJobExecutionRecord, String?> = createField(DSL.name("exit_code"), SQLDataType.VARCHAR(2500), this, "")

    /**
     * The column <code>public.batch_job_execution.exit_message</code>.
     */
    val EXIT_MESSAGE: TableField<BatchJobExecutionRecord, String?> = createField(DSL.name("exit_message"), SQLDataType.VARCHAR(2500), this, "")

    /**
     * The column <code>public.batch_job_execution.last_updated</code>.
     */
    val LAST_UPDATED: TableField<BatchJobExecutionRecord, LocalDateTime?> = createField(DSL.name("last_updated"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column
     * <code>public.batch_job_execution.job_configuration_location</code>.
     */
    val JOB_CONFIGURATION_LOCATION: TableField<BatchJobExecutionRecord, String?> = createField(DSL.name("job_configuration_location"), SQLDataType.VARCHAR(2500), this, "")

    private constructor(alias: Name, aliased: Table<BatchJobExecutionRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<BatchJobExecutionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.batch_job_execution</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.batch_job_execution</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.batch_job_execution</code> table reference
     */
    constructor(): this(DSL.name("batch_job_execution"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, BatchJobExecutionRecord>): this(Internal.createPathAlias(child, key), child, key, BATCH_JOB_EXECUTION, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<BatchJobExecutionRecord> = BATCH_JOB_EXECUTION_PKEY
    override fun getReferences(): List<ForeignKey<BatchJobExecutionRecord, *>> = listOf(BATCH_JOB_EXECUTION__JOB_INST_EXEC_FK)

    private lateinit var _batchJobInstance: BatchJobInstance

    /**
     * Get the implicit join path to the <code>public.batch_job_instance</code>
     * table.
     */
    fun batchJobInstance(): BatchJobInstance {
        if (!this::_batchJobInstance.isInitialized)
            _batchJobInstance = BatchJobInstance(this, BATCH_JOB_EXECUTION__JOB_INST_EXEC_FK)

        return _batchJobInstance;
    }

    val batchJobInstance: BatchJobInstance
        get(): BatchJobInstance = batchJobInstance()
    override fun `as`(alias: String): BatchJobExecution = BatchJobExecution(DSL.name(alias), this)
    override fun `as`(alias: Name): BatchJobExecution = BatchJobExecution(alias, this)
    override fun `as`(alias: Table<*>): BatchJobExecution = BatchJobExecution(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BatchJobExecution = BatchJobExecution(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BatchJobExecution = BatchJobExecution(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BatchJobExecution = BatchJobExecution(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row11<Long?, Long?, Long?, LocalDateTime?, LocalDateTime?, LocalDateTime?, String?, String?, String?, LocalDateTime?, String?> = super.fieldsRow() as Row11<Long?, Long?, Long?, LocalDateTime?, LocalDateTime?, LocalDateTime?, String?, String?, String?, LocalDateTime?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, Long?, LocalDateTime?, LocalDateTime?, LocalDateTime?, String?, String?, String?, LocalDateTime?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, Long?, LocalDateTime?, LocalDateTime?, LocalDateTime?, String?, String?, String?, LocalDateTime?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
