/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.tables.records.CmeProductsRecord

import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmeProducts(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CmeProductsRecord>?,
    aliased: Table<CmeProductsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CmeProductsRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.cme_products</code>
         */
        val CME_PRODUCTS: CmeProducts = CmeProducts()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CmeProductsRecord> = CmeProductsRecord::class.java

    /**
     * The column <code>public.cme_products.owner_id</code>.
     */
    val OWNER_ID: TableField<CmeProductsRecord, String?> = createField(DSL.name("owner_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cme_products.percent</code>.
     */
    val PERCENT: TableField<CmeProductsRecord, Double?> = createField(DSL.name("percent"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>public.cme_products.product</code>.
     */
    val PRODUCT: TableField<CmeProductsRecord, String?> = createField(DSL.name("product"), SQLDataType.CHAR(37), this, "")

    private constructor(alias: Name, aliased: Table<CmeProductsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CmeProductsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.cme_products</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.cme_products</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.cme_products</code> table reference
     */
    constructor(): this(DSL.name("cme_products"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CmeProductsRecord>): this(Internal.createPathAlias(child, key), child, key, CME_PRODUCTS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): CmeProducts = CmeProducts(DSL.name(alias), this)
    override fun `as`(alias: Name): CmeProducts = CmeProducts(alias, this)
    override fun `as`(alias: Table<*>): CmeProducts = CmeProducts(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CmeProducts = CmeProducts(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CmeProducts = CmeProducts(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CmeProducts = CmeProducts(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<String?, Double?, String?> = super.fieldsRow() as Row3<String?, Double?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, Double?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, Double?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
