/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.keys.CME_REQUIRED_DOCUMENT_PKEY
import com.squer.prorpel.jooq.tables.records.CmeRequiredDocumentRecord

import java.time.OffsetDateTime
import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row11
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmeRequiredDocument(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CmeRequiredDocumentRecord>?,
    aliased: Table<CmeRequiredDocumentRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CmeRequiredDocumentRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.cme_required_document</code>
         */
        val CME_REQUIRED_DOCUMENT: CmeRequiredDocument = CmeRequiredDocument()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CmeRequiredDocumentRecord> = CmeRequiredDocumentRecord::class.java

    /**
     * The column <code>public.cme_required_document.owner_id</code>.
     */
    val OWNER_ID: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("owner_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cme_required_document.path</code>.
     */
    val PATH: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("path"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cme_required_document.id</code>.
     */
    val ID: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("id"), SQLDataType.CHAR(37).nullable(false), this, "")

    /**
     * The column <code>public.cme_required_document.updated_by</code>.
     */
    val UPDATED_BY: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cme_required_document.created_by</code>.
     */
    val CREATED_BY: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("created_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cme_required_document.updated_on</code>.
     */
    val UPDATED_ON: TableField<CmeRequiredDocumentRecord, OffsetDateTime?> = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cme_required_document.type</code>.
     */
    val TYPE: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("type"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cme_required_document.created_on</code>.
     */
    val CREATED_ON: TableField<CmeRequiredDocumentRecord, OffsetDateTime?> = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cme_required_document.stale_id</code>.
     */
    val STALE_ID: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("stale_id"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cme_required_document.value</code>.
     */
    val VALUE: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("value"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.cme_required_document.file_name</code>.
     */
    val FILE_NAME: TableField<CmeRequiredDocumentRecord, String?> = createField(DSL.name("file_name"), SQLDataType.VARCHAR(100), this, "")

    private constructor(alias: Name, aliased: Table<CmeRequiredDocumentRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CmeRequiredDocumentRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.cme_required_document</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.cme_required_document</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.cme_required_document</code> table reference
     */
    constructor(): this(DSL.name("cme_required_document"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CmeRequiredDocumentRecord>): this(Internal.createPathAlias(child, key), child, key, CME_REQUIRED_DOCUMENT, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<CmeRequiredDocumentRecord> = CME_REQUIRED_DOCUMENT_PKEY
    override fun `as`(alias: String): CmeRequiredDocument = CmeRequiredDocument(DSL.name(alias), this)
    override fun `as`(alias: Name): CmeRequiredDocument = CmeRequiredDocument(alias, this)
    override fun `as`(alias: Table<*>): CmeRequiredDocument = CmeRequiredDocument(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CmeRequiredDocument = CmeRequiredDocument(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CmeRequiredDocument = CmeRequiredDocument(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CmeRequiredDocument = CmeRequiredDocument(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row11<String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, String?, String?> = super.fieldsRow() as Row11<String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
