/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.tables.records.CmeVendorBankDetailRecord

import java.time.OffsetDateTime
import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row17
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmeVendorBankDetail(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CmeVendorBankDetailRecord>?,
    aliased: Table<CmeVendorBankDetailRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CmeVendorBankDetailRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.cme_vendor_bank_detail</code>
         */
        val CME_VENDOR_BANK_DETAIL: CmeVendorBankDetail = CmeVendorBankDetail()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CmeVendorBankDetailRecord> = CmeVendorBankDetailRecord::class.java

    /**
     * The column <code>public.cme_vendor_bank_detail.vendor_name</code>.
     */
    val VENDOR_NAME: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("vendor_name"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.id</code>.
     */
    val ID: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column
     * <code>public.cme_vendor_bank_detail.service_provider_no</code>.
     */
    val SERVICE_PROVIDER_NO: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("service_provider_no"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.created_by</code>.
     */
    val CREATED_BY: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("created_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.address</code>.
     */
    val ADDRESS: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.comments</code>.
     */
    val COMMENTS: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("comments"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.cmvdr_id</code>.
     */
    val CMVDR_ID: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("cmvdr_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.bank_name</code>.
     */
    val BANK_NAME: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("bank_name"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.stale_id</code>.
     */
    val STALE_ID: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("stale_id"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.branch_name</code>.
     */
    val BRANCH_NAME: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("branch_name"), SQLDataType.VARCHAR(25), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.beneficiary_name</code>.
     */
    val BENEFICIARY_NAME: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("beneficiary_name"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.account_no</code>.
     */
    val ACCOUNT_NO: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("account_no"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.updated_by</code>.
     */
    val UPDATED_BY: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.updated_on</code>.
     */
    val UPDATED_ON: TableField<CmeVendorBankDetailRecord, OffsetDateTime?> = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.ifsc_code</code>.
     */
    val IFSC_CODE: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("ifsc_code"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.created_on</code>.
     */
    val CREATED_ON: TableField<CmeVendorBankDetailRecord, OffsetDateTime?> = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cme_vendor_bank_detail.partner_id</code>.
     */
    val PARTNER_ID: TableField<CmeVendorBankDetailRecord, String?> = createField(DSL.name("partner_id"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<CmeVendorBankDetailRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CmeVendorBankDetailRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.cme_vendor_bank_detail</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.cme_vendor_bank_detail</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.cme_vendor_bank_detail</code> table reference
     */
    constructor(): this(DSL.name("cme_vendor_bank_detail"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CmeVendorBankDetailRecord>): this(Internal.createPathAlias(child, key), child, key, CME_VENDOR_BANK_DETAIL, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): CmeVendorBankDetail = CmeVendorBankDetail(DSL.name(alias), this)
    override fun `as`(alias: Name): CmeVendorBankDetail = CmeVendorBankDetail(alias, this)
    override fun `as`(alias: Table<*>): CmeVendorBankDetail = CmeVendorBankDetail(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CmeVendorBankDetail = CmeVendorBankDetail(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CmeVendorBankDetail = CmeVendorBankDetail(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CmeVendorBankDetail = CmeVendorBankDetail(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row17 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row17<String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.fieldsRow() as Row17<String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
