/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.tables.records.CmtChemistRecord

import java.time.OffsetDateTime
import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row15
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmtChemist(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CmtChemistRecord>?,
    aliased: Table<CmtChemistRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CmtChemistRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.cmt_chemist</code>
         */
        val CMT_CHEMIST: CmtChemist = CmtChemist()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CmtChemistRecord> = CmtChemistRecord::class.java

    /**
     * The column <code>public.cmt_chemist.name</code>.
     */
    val NAME: TableField<CmtChemistRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cmt_chemist.status_id</code>.
     */
    val STATUS_ID: TableField<CmtChemistRecord, String?> = createField(DSL.name("status_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_chemist.updated_on</code>.
     */
    val UPDATED_ON: TableField<CmtChemistRecord, OffsetDateTime?> = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cmt_chemist.classification_id</code>.
     */
    val CLASSIFICATION_ID: TableField<CmtChemistRecord, String?> = createField(DSL.name("classification_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_chemist.stale_id</code>.
     */
    val STALE_ID: TableField<CmtChemistRecord, Long?> = createField(DSL.name("stale_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.cmt_chemist.ci_name</code>.
     */
    val CI_NAME: TableField<CmtChemistRecord, String?> = createField(DSL.name("ci_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cmt_chemist.created_on</code>.
     */
    val CREATED_ON: TableField<CmtChemistRecord, OffsetDateTime?> = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cmt_chemist.location_id</code>.
     */
    val LOCATION_ID: TableField<CmtChemistRecord, String?> = createField(DSL.name("location_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_chemist.id</code>.
     */
    val ID: TableField<CmtChemistRecord, String?> = createField(DSL.name("id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_chemist.updated_by</code>.
     */
    val UPDATED_BY: TableField<CmtChemistRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_chemist.code</code>.
     */
    val CODE: TableField<CmtChemistRecord, String?> = createField(DSL.name("code"), SQLDataType.VARCHAR(25), this, "")

    /**
     * The column <code>public.cmt_chemist.created_by</code>.
     */
    val CREATED_BY: TableField<CmtChemistRecord, String?> = createField(DSL.name("created_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_chemist.external_id</code>.
     */
    val EXTERNAL_ID: TableField<CmtChemistRecord, String?> = createField(DSL.name("external_id"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.cmt_chemist.account_id</code>.
     */
    val ACCOUNT_ID: TableField<CmtChemistRecord, String?> = createField(DSL.name("account_id"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.cmt_chemist.required_frequency</code>.
     */
    val REQUIRED_FREQUENCY: TableField<CmtChemistRecord, Int?> = createField(DSL.name("required_frequency"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<CmtChemistRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CmtChemistRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.cmt_chemist</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.cmt_chemist</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.cmt_chemist</code> table reference
     */
    constructor(): this(DSL.name("cmt_chemist"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CmtChemistRecord>): this(Internal.createPathAlias(child, key), child, key, CMT_CHEMIST, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): CmtChemist = CmtChemist(DSL.name(alias), this)
    override fun `as`(alias: Name): CmtChemist = CmtChemist(alias, this)
    override fun `as`(alias: Table<*>): CmtChemist = CmtChemist(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CmtChemist = CmtChemist(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CmtChemist = CmtChemist(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CmtChemist = CmtChemist(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row15<String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, String?, String?, Int?> = super.fieldsRow() as Row15<String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, String?, String?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, String?, String?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, String?, String?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
