/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.keys.CMT_LOCATION_PKEY
import com.squer.prorpel.jooq.tables.records.CmtLocationOldRecord

import java.time.OffsetDateTime
import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row14
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmtLocationOld(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CmtLocationOldRecord>?,
    aliased: Table<CmtLocationOldRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CmtLocationOldRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.cmt_location_old</code>
         */
        val CMT_LOCATION_OLD: CmtLocationOld = CmtLocationOld()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CmtLocationOldRecord> = CmtLocationOldRecord::class.java

    /**
     * The column <code>public.cmt_location_old.updated_on</code>.
     */
    val UPDATED_ON: TableField<CmtLocationOldRecord, OffsetDateTime?> = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cmt_location_old.ci_name</code>.
     */
    val CI_NAME: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("ci_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cmt_location_old.created_on</code>.
     */
    val CREATED_ON: TableField<CmtLocationOldRecord, OffsetDateTime?> = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cmt_location_old.external_id</code>.
     */
    val EXTERNAL_ID: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("external_id"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.cmt_location_old.updated_by</code>.
     */
    val UPDATED_BY: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_location_old.parent_id</code>.
     */
    val PARENT_ID: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("parent_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_location_old.name</code>.
     */
    val NAME: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cmt_location_old.status_id</code>.
     */
    val STATUS_ID: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("status_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_location_old.stale_id</code>.
     */
    val STALE_ID: TableField<CmtLocationOldRecord, Long?> = createField(DSL.name("stale_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.cmt_location_old.heirarchy_id</code>.
     */
    val HEIRARCHY_ID: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("heirarchy_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_location_old.id</code>.
     */
    val ID: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("id"), SQLDataType.CHAR(37).nullable(false), this, "")

    /**
     * The column <code>public.cmt_location_old.created_by</code>.
     */
    val CREATED_BY: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("created_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_location_old.sap_code</code>.
     */
    val SAP_CODE: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("sap_code"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.cmt_location_old.division_id</code>.
     */
    val DIVISION_ID: TableField<CmtLocationOldRecord, String?> = createField(DSL.name("division_id"), SQLDataType.CHAR(37), this, "")

    private constructor(alias: Name, aliased: Table<CmtLocationOldRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CmtLocationOldRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.cmt_location_old</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.cmt_location_old</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.cmt_location_old</code> table reference
     */
    constructor(): this(DSL.name("cmt_location_old"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CmtLocationOldRecord>): this(Internal.createPathAlias(child, key), child, key, CMT_LOCATION_OLD, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<CmtLocationOldRecord> = CMT_LOCATION_PKEY
    override fun `as`(alias: String): CmtLocationOld = CmtLocationOld(DSL.name(alias), this)
    override fun `as`(alias: Name): CmtLocationOld = CmtLocationOld(alias, this)
    override fun `as`(alias: Table<*>): CmtLocationOld = CmtLocationOld(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CmtLocationOld = CmtLocationOld(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CmtLocationOld = CmtLocationOld(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CmtLocationOld = CmtLocationOld(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row14<OffsetDateTime?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?, String?> = super.fieldsRow() as Row14<OffsetDateTime?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (OffsetDateTime?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (OffsetDateTime?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
