/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.keys.CMT_STOCKIST_PKEY
import com.squer.prorpel.jooq.tables.records.CmtStockistRecord

import java.time.OffsetDateTime
import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row12
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmtStockist(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CmtStockistRecord>?,
    aliased: Table<CmtStockistRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CmtStockistRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.cmt_stockist</code>
         */
        val CMT_STOCKIST: CmtStockist = CmtStockist()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CmtStockistRecord> = CmtStockistRecord::class.java

    /**
     * The column <code>public.cmt_stockist.name</code>.
     */
    val NAME: TableField<CmtStockistRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cmt_stockist.updated_on</code>.
     */
    val UPDATED_ON: TableField<CmtStockistRecord, OffsetDateTime?> = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cmt_stockist.stale_id</code>.
     */
    val STALE_ID: TableField<CmtStockistRecord, Long?> = createField(DSL.name("stale_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.cmt_stockist.ci_name</code>.
     */
    val CI_NAME: TableField<CmtStockistRecord, String?> = createField(DSL.name("ci_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cmt_stockist.created_on</code>.
     */
    val CREATED_ON: TableField<CmtStockistRecord, OffsetDateTime?> = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.cmt_stockist.stockist_code</code>.
     */
    val STOCKIST_CODE: TableField<CmtStockistRecord, String?> = createField(DSL.name("stockist_code"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.cmt_stockist.id</code>.
     */
    val ID: TableField<CmtStockistRecord, String?> = createField(DSL.name("id"), SQLDataType.CHAR(37).nullable(false), this, "")

    /**
     * The column <code>public.cmt_stockist.status_id</code>.
     */
    val STATUS_ID: TableField<CmtStockistRecord, String?> = createField(DSL.name("status_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_stockist.updated_by</code>.
     */
    val UPDATED_BY: TableField<CmtStockistRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_stockist.created_by</code>.
     */
    val CREATED_BY: TableField<CmtStockistRecord, String?> = createField(DSL.name("created_by"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.cmt_stockist.external_id</code>.
     */
    val EXTERNAL_ID: TableField<CmtStockistRecord, String?> = createField(DSL.name("external_id"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.cmt_stockist.account_id</code>.
     */
    val ACCOUNT_ID: TableField<CmtStockistRecord, String?> = createField(DSL.name("account_id"), SQLDataType.VARCHAR(50), this, "")

    private constructor(alias: Name, aliased: Table<CmtStockistRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CmtStockistRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.cmt_stockist</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.cmt_stockist</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.cmt_stockist</code> table reference
     */
    constructor(): this(DSL.name("cmt_stockist"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CmtStockistRecord>): this(Internal.createPathAlias(child, key), child, key, CMT_STOCKIST, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<CmtStockistRecord> = CMT_STOCKIST_PKEY
    override fun `as`(alias: String): CmtStockist = CmtStockist(DSL.name(alias), this)
    override fun `as`(alias: Name): CmtStockist = CmtStockist(alias, this)
    override fun `as`(alias: Table<*>): CmtStockist = CmtStockist(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CmtStockist = CmtStockist(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CmtStockist = CmtStockist(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CmtStockist = CmtStockist(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row12<String?, OffsetDateTime?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, String?, String?> = super.fieldsRow() as Row12<String?, OffsetDateTime?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, OffsetDateTime?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, OffsetDateTime?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
