/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.indexes.DSH_CONSOLIDATED_LOCATION_COVERAGE_DIVISION_ID_INDEX
import com.squer.prorpel.jooq.indexes.DSH_CONSOLIDATED_LOCATION_COVERAGE_LOCATION_ID_INDEX
import com.squer.prorpel.jooq.indexes.DSH_CONSOLIDATED_LOCATION_COVERAGE_YEARMONTH_INDEX
import com.squer.prorpel.jooq.tables.records.DshConsolidatedLocationCoverageRecord

import java.util.function.Function

import javax.annotation.processing.Generated

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row19
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshConsolidatedLocationCoverage(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, DshConsolidatedLocationCoverageRecord>?,
    aliased: Table<DshConsolidatedLocationCoverageRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<DshConsolidatedLocationCoverageRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.dsh_consolidated_location_coverage</code>
         */
        val DSH_CONSOLIDATED_LOCATION_COVERAGE: DshConsolidatedLocationCoverage = DshConsolidatedLocationCoverage()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DshConsolidatedLocationCoverageRecord> = DshConsolidatedLocationCoverageRecord::class.java

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.division_id</code>.
     */
    val DIVISION_ID: TableField<DshConsolidatedLocationCoverageRecord, String?> = createField(DSL.name("division_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.location_id</code>.
     */
    val LOCATION_ID: TableField<DshConsolidatedLocationCoverageRecord, String?> = createField(DSL.name("location_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.dsh_consolidated_location_coverage.month</code>.
     */
    val MONTH: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("month"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.dsh_consolidated_location_coverage.year</code>.
     */
    val YEAR: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("year"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.yearmonth</code>.
     */
    val YEARMONTH: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("yearmonth"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.a_coverage</code>.
     */
    val A_COVERAGE: TableField<DshConsolidatedLocationCoverageRecord, Double?> = createField(DSL.name("a_coverage"), SQLDataType.DOUBLE, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.b_coverage</code>.
     */
    val B_COVERAGE: TableField<DshConsolidatedLocationCoverageRecord, Double?> = createField(DSL.name("b_coverage"), SQLDataType.DOUBLE, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.c_coverage</code>.
     */
    val C_COVERAGE: TableField<DshConsolidatedLocationCoverageRecord, Double?> = createField(DSL.name("c_coverage"), SQLDataType.DOUBLE, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.total_coverage</code>.
     */
    val TOTAL_COVERAGE: TableField<DshConsolidatedLocationCoverageRecord, Double?> = createField(DSL.name("total_coverage"), SQLDataType.DOUBLE, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.call_average</code>.
     */
    val CALL_AVERAGE: TableField<DshConsolidatedLocationCoverageRecord, Double?> = createField(DSL.name("call_average"), SQLDataType.DOUBLE, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.field_days</code>.
     */
    val FIELD_DAYS: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("field_days"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.total_doctors</code>.
     */
    val TOTAL_DOCTORS: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("total_doctors"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.total_doctor_visit</code>.
     */
    val TOTAL_DOCTOR_VISIT: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("total_doctor_visit"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.total_a_doctors</code>.
     */
    val TOTAL_A_DOCTORS: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("total_a_doctors"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.total_b_doctors</code>.
     */
    val TOTAL_B_DOCTORS: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("total_b_doctors"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.total_c_doctors</code>.
     */
    val TOTAL_C_DOCTORS: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("total_c_doctors"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.distinct_a_visits</code>.
     */
    val DISTINCT_A_VISITS: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("distinct_a_visits"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.distinct_b_visits</code>.
     */
    val DISTINCT_B_VISITS: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("distinct_b_visits"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_coverage.distinct_c_visits</code>.
     */
    val DISTINCT_C_VISITS: TableField<DshConsolidatedLocationCoverageRecord, Int?> = createField(DSL.name("distinct_c_visits"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<DshConsolidatedLocationCoverageRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<DshConsolidatedLocationCoverageRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.dsh_consolidated_location_coverage</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.dsh_consolidated_location_coverage</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.dsh_consolidated_location_coverage</code> table
     * reference
     */
    constructor(): this(DSL.name("dsh_consolidated_location_coverage"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, DshConsolidatedLocationCoverageRecord>): this(Internal.createPathAlias(child, key), child, key, DSH_CONSOLIDATED_LOCATION_COVERAGE, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(DSH_CONSOLIDATED_LOCATION_COVERAGE_DIVISION_ID_INDEX, DSH_CONSOLIDATED_LOCATION_COVERAGE_LOCATION_ID_INDEX, DSH_CONSOLIDATED_LOCATION_COVERAGE_YEARMONTH_INDEX)
    override fun `as`(alias: String): DshConsolidatedLocationCoverage = DshConsolidatedLocationCoverage(DSL.name(alias), this)
    override fun `as`(alias: Name): DshConsolidatedLocationCoverage = DshConsolidatedLocationCoverage(alias, this)
    override fun `as`(alias: Table<*>): DshConsolidatedLocationCoverage = DshConsolidatedLocationCoverage(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DshConsolidatedLocationCoverage = DshConsolidatedLocationCoverage(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DshConsolidatedLocationCoverage = DshConsolidatedLocationCoverage(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DshConsolidatedLocationCoverage = DshConsolidatedLocationCoverage(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row19 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row19<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row19<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
