/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.indexes.IDX_LOC_SS_DIVISION
import com.squer.prorpel.jooq.indexes.IDX_LOC_SS_LOCATION
import com.squer.prorpel.jooq.indexes.IDX_LOC_SS_MONTH
import com.squer.prorpel.jooq.indexes.IDX_LOC_SS_YEAR
import com.squer.prorpel.jooq.indexes.IDX_LOC_SS_YEARMONTH
import com.squer.prorpel.jooq.tables.records.DshConsolidatedLocationSecondarySalesRecord

import java.util.function.Function

import javax.annotation.processing.Generated

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshConsolidatedLocationSecondarySales(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, DshConsolidatedLocationSecondarySalesRecord>?,
    aliased: Table<DshConsolidatedLocationSecondarySalesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<DshConsolidatedLocationSecondarySalesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.dsh_consolidated_location_secondary_sales</code>
         */
        val DSH_CONSOLIDATED_LOCATION_SECONDARY_SALES: DshConsolidatedLocationSecondarySales = DshConsolidatedLocationSecondarySales()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DshConsolidatedLocationSecondarySalesRecord> = DshConsolidatedLocationSecondarySalesRecord::class.java

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.division_id</code>.
     */
    val DIVISION_ID: TableField<DshConsolidatedLocationSecondarySalesRecord, String?> = createField(DSL.name("division_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.location_id</code>.
     */
    val LOCATION_ID: TableField<DshConsolidatedLocationSecondarySalesRecord, String?> = createField(DSL.name("location_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.month</code>.
     */
    val MONTH: TableField<DshConsolidatedLocationSecondarySalesRecord, Int?> = createField(DSL.name("month"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.year</code>.
     */
    val YEAR: TableField<DshConsolidatedLocationSecondarySalesRecord, Int?> = createField(DSL.name("year"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.yearmonth</code>.
     */
    val YEARMONTH: TableField<DshConsolidatedLocationSecondarySalesRecord, Int?> = createField(DSL.name("yearmonth"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.secondary_units</code>.
     */
    val SECONDARY_UNITS: TableField<DshConsolidatedLocationSecondarySalesRecord, Int?> = createField(DSL.name("secondary_units"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.closing_units</code>.
     */
    val CLOSING_UNITS: TableField<DshConsolidatedLocationSecondarySalesRecord, Int?> = createField(DSL.name("closing_units"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.secondary_value</code>.
     */
    val SECONDARY_VALUE: TableField<DshConsolidatedLocationSecondarySalesRecord, Double?> = createField(DSL.name("secondary_value"), SQLDataType.DOUBLE, this, "")

    /**
     * The column
     * <code>public.dsh_consolidated_location_secondary_sales.closing_value</code>.
     */
    val CLOSING_VALUE: TableField<DshConsolidatedLocationSecondarySalesRecord, Double?> = createField(DSL.name("closing_value"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<DshConsolidatedLocationSecondarySalesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<DshConsolidatedLocationSecondarySalesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased
     * <code>public.dsh_consolidated_location_secondary_sales</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased
     * <code>public.dsh_consolidated_location_secondary_sales</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.dsh_consolidated_location_secondary_sales</code>
     * table reference
     */
    constructor(): this(DSL.name("dsh_consolidated_location_secondary_sales"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, DshConsolidatedLocationSecondarySalesRecord>): this(Internal.createPathAlias(child, key), child, key, DSH_CONSOLIDATED_LOCATION_SECONDARY_SALES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_LOC_SS_DIVISION, IDX_LOC_SS_LOCATION, IDX_LOC_SS_MONTH, IDX_LOC_SS_YEAR, IDX_LOC_SS_YEARMONTH)
    override fun `as`(alias: String): DshConsolidatedLocationSecondarySales = DshConsolidatedLocationSecondarySales(DSL.name(alias), this)
    override fun `as`(alias: Name): DshConsolidatedLocationSecondarySales = DshConsolidatedLocationSecondarySales(alias, this)
    override fun `as`(alias: Table<*>): DshConsolidatedLocationSecondarySales = DshConsolidatedLocationSecondarySales(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DshConsolidatedLocationSecondarySales = DshConsolidatedLocationSecondarySales(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DshConsolidatedLocationSecondarySales = DshConsolidatedLocationSecondarySales(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DshConsolidatedLocationSecondarySales = DshConsolidatedLocationSecondarySales(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row9<String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?> = super.fieldsRow() as Row9<String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
