/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.tables.records.DshDatewiseSalesRecord

import java.time.LocalDateTime
import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshDatewiseSales(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, DshDatewiseSalesRecord>?,
    aliased: Table<DshDatewiseSalesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<DshDatewiseSalesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.dsh_datewise_sales</code>
         */
        val DSH_DATEWISE_SALES: DshDatewiseSales = DshDatewiseSales()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DshDatewiseSalesRecord> = DshDatewiseSalesRecord::class.java

    /**
     * The column <code>public.dsh_datewise_sales.division_id</code>.
     */
    val DIVISION_ID: TableField<DshDatewiseSalesRecord, String?> = createField(DSL.name("division_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.dsh_datewise_sales.location_id</code>.
     */
    val LOCATION_ID: TableField<DshDatewiseSalesRecord, String?> = createField(DSL.name("location_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.dsh_datewise_sales.brand_id</code>.
     */
    val BRAND_ID: TableField<DshDatewiseSalesRecord, String?> = createField(DSL.name("brand_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.dsh_datewise_sales.invoice_date</code>.
     */
    val INVOICE_DATE: TableField<DshDatewiseSalesRecord, LocalDateTime?> = createField(DSL.name("invoice_date"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.dsh_datewise_sales.quantity</code>.
     */
    val QUANTITY: TableField<DshDatewiseSalesRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.dsh_datewise_sales.amount</code>.
     */
    val AMOUNT: TableField<DshDatewiseSalesRecord, Double?> = createField(DSL.name("amount"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<DshDatewiseSalesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<DshDatewiseSalesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.dsh_datewise_sales</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.dsh_datewise_sales</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.dsh_datewise_sales</code> table reference
     */
    constructor(): this(DSL.name("dsh_datewise_sales"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, DshDatewiseSalesRecord>): this(Internal.createPathAlias(child, key), child, key, DSH_DATEWISE_SALES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): DshDatewiseSales = DshDatewiseSales(DSL.name(alias), this)
    override fun `as`(alias: Name): DshDatewiseSales = DshDatewiseSales(alias, this)
    override fun `as`(alias: Table<*>): DshDatewiseSales = DshDatewiseSales(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DshDatewiseSales = DshDatewiseSales(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DshDatewiseSales = DshDatewiseSales(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DshDatewiseSales = DshDatewiseSales(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<String?, String?, String?, LocalDateTime?, Int?, Double?> = super.fieldsRow() as Row6<String?, String?, String?, LocalDateTime?, Int?, Double?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, LocalDateTime?, Int?, Double?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, LocalDateTime?, Int?, Double?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
