/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.indexes.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY_BRA
import com.squer.prorpel.jooq.indexes.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY_DIV
import com.squer.prorpel.jooq.indexes.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY_LOC
import com.squer.prorpel.jooq.indexes.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY_YEA
import com.squer.prorpel.jooq.tables.records.DshLocationwiseConsolidatedRetailerProductAvailabilityRecord

import java.util.function.Function

import javax.annotation.processing.Generated

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshLocationwiseConsolidatedRetailerProductAvailability(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, DshLocationwiseConsolidatedRetailerProductAvailabilityRecord>?,
    aliased: Table<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.dsh_locationwise_consolidated_retailer_product_availability</code>
         */
        val DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY: DshLocationwiseConsolidatedRetailerProductAvailability = DshLocationwiseConsolidatedRetailerProductAvailability()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord> = DshLocationwiseConsolidatedRetailerProductAvailabilityRecord::class.java

    /**
     * The column
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability.division_id</code>.
     */
    val DIVISION_ID: TableField<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord, String?> = createField(DSL.name("division_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability.location_id</code>.
     */
    val LOCATION_ID: TableField<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord, String?> = createField(DSL.name("location_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability.brand_id</code>.
     */
    val BRAND_ID: TableField<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord, String?> = createField(DSL.name("brand_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability.month</code>.
     */
    val MONTH: TableField<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord, Int?> = createField(DSL.name("month"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability.year</code>.
     */
    val YEAR: TableField<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord, Int?> = createField(DSL.name("year"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability.yearmonth</code>.
     */
    val YEARMONTH: TableField<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord, Int?> = createField(DSL.name("yearmonth"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability.total</code>.
     */
    val TOTAL: TableField<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord, Int?> = createField(DSL.name("total"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability.retailers</code>.
     */
    val RETAILERS: TableField<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord, Int?> = createField(DSL.name("retailers"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a
     * <code>public.dsh_locationwise_consolidated_retailer_product_availability</code>
     * table reference
     */
    constructor(): this(DSL.name("dsh_locationwise_consolidated_retailer_product_availability"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, DshLocationwiseConsolidatedRetailerProductAvailabilityRecord>): this(Internal.createPathAlias(child, key), child, key, DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY_BRA, DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY_DIV, DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY_LOC, DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY_YEA)
    override fun `as`(alias: String): DshLocationwiseConsolidatedRetailerProductAvailability = DshLocationwiseConsolidatedRetailerProductAvailability(DSL.name(alias), this)
    override fun `as`(alias: Name): DshLocationwiseConsolidatedRetailerProductAvailability = DshLocationwiseConsolidatedRetailerProductAvailability(alias, this)
    override fun `as`(alias: Table<*>): DshLocationwiseConsolidatedRetailerProductAvailability = DshLocationwiseConsolidatedRetailerProductAvailability(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DshLocationwiseConsolidatedRetailerProductAvailability = DshLocationwiseConsolidatedRetailerProductAvailability(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DshLocationwiseConsolidatedRetailerProductAvailability = DshLocationwiseConsolidatedRetailerProductAvailability(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DshLocationwiseConsolidatedRetailerProductAvailability = DshLocationwiseConsolidatedRetailerProductAvailability(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<String?, String?, String?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row8<String?, String?, String?, Int?, Int?, Int?, Int?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, Int?, Int?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, Int?, Int?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
