/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.tables.records.DshSalesSubcustomerMappingRecord

import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshSalesSubcustomerMapping(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, DshSalesSubcustomerMappingRecord>?,
    aliased: Table<DshSalesSubcustomerMappingRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<DshSalesSubcustomerMappingRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.dsh_sales_subcustomer_mapping</code>
         */
        val DSH_SALES_SUBCUSTOMER_MAPPING: DshSalesSubcustomerMapping = DshSalesSubcustomerMapping()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DshSalesSubcustomerMappingRecord> = DshSalesSubcustomerMappingRecord::class.java

    /**
     * The column
     * <code>public.dsh_sales_subcustomer_mapping.subcustomer_code</code>.
     */
    val SUBCUSTOMER_CODE: TableField<DshSalesSubcustomerMappingRecord, String?> = createField(DSL.name("subcustomer_code"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column
     * <code>public.dsh_sales_subcustomer_mapping.subcustomer_name</code>.
     */
    val SUBCUSTOMER_NAME: TableField<DshSalesSubcustomerMappingRecord, String?> = createField(DSL.name("subcustomer_name"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column
     * <code>public.dsh_sales_subcustomer_mapping.subcustomer_sap</code>.
     */
    val SUBCUSTOMER_SAP: TableField<DshSalesSubcustomerMappingRecord, String?> = createField(DSL.name("subcustomer_sap"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.dsh_sales_subcustomer_mapping.sap_code</code>.
     */
    val SAP_CODE: TableField<DshSalesSubcustomerMappingRecord, String?> = createField(DSL.name("sap_code"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.dsh_sales_subcustomer_mapping.division_id</code>.
     */
    val DIVISION_ID: TableField<DshSalesSubcustomerMappingRecord, String?> = createField(DSL.name("division_id"), SQLDataType.CHAR(37), this, "")

    private constructor(alias: Name, aliased: Table<DshSalesSubcustomerMappingRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<DshSalesSubcustomerMappingRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.dsh_sales_subcustomer_mapping</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.dsh_sales_subcustomer_mapping</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.dsh_sales_subcustomer_mapping</code> table
     * reference
     */
    constructor(): this(DSL.name("dsh_sales_subcustomer_mapping"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, DshSalesSubcustomerMappingRecord>): this(Internal.createPathAlias(child, key), child, key, DSH_SALES_SUBCUSTOMER_MAPPING, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): DshSalesSubcustomerMapping = DshSalesSubcustomerMapping(DSL.name(alias), this)
    override fun `as`(alias: Name): DshSalesSubcustomerMapping = DshSalesSubcustomerMapping(alias, this)
    override fun `as`(alias: Table<*>): DshSalesSubcustomerMapping = DshSalesSubcustomerMapping(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DshSalesSubcustomerMapping = DshSalesSubcustomerMapping(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DshSalesSubcustomerMapping = DshSalesSubcustomerMapping(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DshSalesSubcustomerMapping = DshSalesSubcustomerMapping(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<String?, String?, String?, String?, String?> = super.fieldsRow() as Row5<String?, String?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
