/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.keys.FMK_SECURITY_PRIVILEGE_PKEY
import com.squer.prorpel.jooq.tables.records.FmkSecurityPrivilegeRecord

import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class FmkSecurityPrivilege(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, FmkSecurityPrivilegeRecord>?,
    aliased: Table<FmkSecurityPrivilegeRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<FmkSecurityPrivilegeRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.fmk_security_privilege</code>
         */
        val FMK_SECURITY_PRIVILEGE: FmkSecurityPrivilege = FmkSecurityPrivilege()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FmkSecurityPrivilegeRecord> = FmkSecurityPrivilegeRecord::class.java

    /**
     * The column <code>public.fmk_security_privilege.id</code>.
     */
    val ID: TableField<FmkSecurityPrivilegeRecord, String?> = createField(DSL.name("id"), SQLDataType.CHAR(37).nullable(false), this, "")

    /**
     * The column <code>public.fmk_security_privilege.priv_description</code>.
     */
    val PRIV_DESCRIPTION: TableField<FmkSecurityPrivilegeRecord, String?> = createField(DSL.name("priv_description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.fmk_security_privilege.priv_name</code>.
     */
    val PRIV_NAME: TableField<FmkSecurityPrivilegeRecord, String?> = createField(DSL.name("priv_name"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<FmkSecurityPrivilegeRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<FmkSecurityPrivilegeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.fmk_security_privilege</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.fmk_security_privilege</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.fmk_security_privilege</code> table reference
     */
    constructor(): this(DSL.name("fmk_security_privilege"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, FmkSecurityPrivilegeRecord>): this(Internal.createPathAlias(child, key), child, key, FMK_SECURITY_PRIVILEGE, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<FmkSecurityPrivilegeRecord> = FMK_SECURITY_PRIVILEGE_PKEY
    override fun `as`(alias: String): FmkSecurityPrivilege = FmkSecurityPrivilege(DSL.name(alias), this)
    override fun `as`(alias: Name): FmkSecurityPrivilege = FmkSecurityPrivilege(alias, this)
    override fun `as`(alias: Table<*>): FmkSecurityPrivilege = FmkSecurityPrivilege(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): FmkSecurityPrivilege = FmkSecurityPrivilege(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FmkSecurityPrivilege = FmkSecurityPrivilege(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FmkSecurityPrivilege = FmkSecurityPrivilege(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<String?, String?, String?> = super.fieldsRow() as Row3<String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
