/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.tables.records.TmpTargetUploadRecord

import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class TmpTargetUpload(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TmpTargetUploadRecord>?,
    aliased: Table<TmpTargetUploadRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TmpTargetUploadRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.tmp_target_upload</code>
         */
        val TMP_TARGET_UPLOAD: TmpTargetUpload = TmpTargetUpload()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TmpTargetUploadRecord> = TmpTargetUploadRecord::class.java

    /**
     * The column <code>public.tmp_target_upload.month</code>.
     */
    val MONTH: TableField<TmpTargetUploadRecord, Int?> = createField(DSL.name("month"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.tmp_target_upload.year</code>.
     */
    val YEAR: TableField<TmpTargetUploadRecord, Int?> = createField(DSL.name("year"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.tmp_target_upload.yearmonth</code>.
     */
    val YEARMONTH: TableField<TmpTargetUploadRecord, Int?> = createField(DSL.name("yearmonth"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.tmp_target_upload.location_id</code>.
     */
    val LOCATION_ID: TableField<TmpTargetUploadRecord, String?> = createField(DSL.name("location_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.tmp_target_upload.brand_id</code>.
     */
    val BRAND_ID: TableField<TmpTargetUploadRecord, String?> = createField(DSL.name("brand_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.tmp_target_upload.target_value</code>.
     */
    val TARGET_VALUE: TableField<TmpTargetUploadRecord, Double?> = createField(DSL.name("target_value"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<TmpTargetUploadRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TmpTargetUploadRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.tmp_target_upload</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.tmp_target_upload</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.tmp_target_upload</code> table reference
     */
    constructor(): this(DSL.name("tmp_target_upload"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TmpTargetUploadRecord>): this(Internal.createPathAlias(child, key), child, key, TMP_TARGET_UPLOAD, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): TmpTargetUpload = TmpTargetUpload(DSL.name(alias), this)
    override fun `as`(alias: Name): TmpTargetUpload = TmpTargetUpload(alias, this)
    override fun `as`(alias: Table<*>): TmpTargetUpload = TmpTargetUpload(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TmpTargetUpload = TmpTargetUpload(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TmpTargetUpload = TmpTargetUpload(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TmpTargetUpload = TmpTargetUpload(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Int?, Int?, Int?, String?, String?, Double?> = super.fieldsRow() as Row6<Int?, Int?, Int?, String?, String?, Double?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, String?, String?, Double?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, String?, String?, Double?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
