/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables


import com.squer.prorpel.jooq.Public
import com.squer.prorpel.jooq.tables.records.TmpTargetDateUploadRecord

import java.util.function.Function

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class TmpTargetDateUpload(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TmpTargetDateUploadRecord>?,
    aliased: Table<TmpTargetDateUploadRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TmpTargetDateUploadRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.tmp_target_date_upload</code>
         */
        val TMP_TARGET_DATE_UPLOAD: TmpTargetDateUpload = TmpTargetDateUpload()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TmpTargetDateUploadRecord> = TmpTargetDateUploadRecord::class.java

    /**
     * The column <code>public.tmp_target_date_upload.sap_code</code>.
     */
    val SAP_CODE: TableField<TmpTargetDateUploadRecord, String?> = createField(DSL.name("sap_code"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.tmp_target_date_upload.brand</code>.
     */
    val BRAND: TableField<TmpTargetDateUploadRecord, String?> = createField(DSL.name("brand"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.tmp_target_date_upload.target</code>.
     */
    val TARGET: TableField<TmpTargetDateUploadRecord, String?> = createField(DSL.name("target"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.tmp_target_date_upload.month</code>.
     */
    val MONTH: TableField<TmpTargetDateUploadRecord, String?> = createField(DSL.name("month"), SQLDataType.VARCHAR(10), this, "")

    /**
     * The column <code>public.tmp_target_date_upload.year</code>.
     */
    val YEAR: TableField<TmpTargetDateUploadRecord, String?> = createField(DSL.name("year"), SQLDataType.VARCHAR(10), this, "")

    /**
     * The column <code>public.tmp_target_date_upload.location_id</code>.
     */
    val LOCATION_ID: TableField<TmpTargetDateUploadRecord, String?> = createField(DSL.name("location_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.tmp_target_date_upload.brand_id</code>.
     */
    val BRAND_ID: TableField<TmpTargetDateUploadRecord, String?> = createField(DSL.name("brand_id"), SQLDataType.CHAR(37), this, "")

    /**
     * The column <code>public.tmp_target_date_upload.error_message</code>.
     */
    val ERROR_MESSAGE: TableField<TmpTargetDateUploadRecord, String?> = createField(DSL.name("error_message"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.tmp_target_date_upload.job_execution_id</code>.
     */
    val JOB_EXECUTION_ID: TableField<TmpTargetDateUploadRecord, Long?> = createField(DSL.name("job_execution_id"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<TmpTargetDateUploadRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TmpTargetDateUploadRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.tmp_target_date_upload</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.tmp_target_date_upload</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.tmp_target_date_upload</code> table reference
     */
    constructor(): this(DSL.name("tmp_target_date_upload"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TmpTargetDateUploadRecord>): this(Internal.createPathAlias(child, key), child, key, TMP_TARGET_DATE_UPLOAD, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): TmpTargetDateUpload = TmpTargetDateUpload(DSL.name(alias), this)
    override fun `as`(alias: Name): TmpTargetDateUpload = TmpTargetDateUpload(alias, this)
    override fun `as`(alias: Table<*>): TmpTargetDateUpload = TmpTargetDateUpload(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TmpTargetDateUpload = TmpTargetDateUpload(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TmpTargetDateUpload = TmpTargetDateUpload(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TmpTargetDateUpload = TmpTargetDateUpload(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row9<String?, String?, String?, String?, String?, String?, String?, String?, Long?> = super.fieldsRow() as Row9<String?, String?, String?, String?, String?, String?, String?, String?, Long?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?, String?, String?, String?, Long?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?, String?, String?, String?, Long?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
