export const INIT_PORTLET_START_ACTION = 'INIT_PORTLET_START_ACTION'

export const COVERAGE_PORTLET_START_ACTION = 'COVERAGE_PORTLET_START_ACTION'
export const COVERAGE_PORTLET_SUCCESS_ACTION = 'COVERAGE_PORTLET_SUCCESS_ACTION'
export const COVERAGE_PORTLET_FAIL_ACTION = 'COVERAGE_PORTLET_FAIL_ACTION'

export const CALL_AVERAGE_PORTLET_START_ACTION = 'CALL_AVERAGE_PORTLET_START_ACTION'
export const CALL_AVERAGE_PORTLET_SUCCESS_ACTION = 'CALL_AVERAGE_PORTLET_SUCCESS_ACTION'
export const CALL_AVERAGE_PORTLET_FAIL_ACTION = 'CALL_AVERAGE_PORTLET_FAIL_ACTION'

export const ORDER_INVOICE_PORTLET_START_ACTION = 'ORDER_INVOICE_PORTLET_START_ACTION'
export const ORDER_INVOICE_PORTLET_SUCCESS_ACTION = 'ORDER_INVOICE_PORTLET_SUCCESS_ACTION'
export const ORDER_INVOICE_PORTLET_FAIL_ACTION = 'ORDER_INVOICE_PORTLET_FAIL_ACTION'

export const JOINT_VISIT_PORTLET_START_ACTION = 'JOINT_VISIT_PORTLET_START_ACTION'
export const JOINT_VISIT_PORTLET_SUCCESS_ACTION = 'JOINT_VISIT_PORTLET_SUCCESS_ACTION'
export const JOINT_VISIT_PORTLET_FAIL_ACTION = 'JOINT_VISIT_PORTLET_FAIL_ACTION'
