/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.CmeHonoranium

import java.time.OffsetDateTime

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmeHonoraniumRecord() : UpdatableRecordImpl<CmeHonoraniumRecord>(CmeHonoranium.CME_HONORANIUM), Record9<String?, String?, Double?, String?, Double?, OffsetDateTime?, OffsetDateTime?, String?, Double?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var updatedBy: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var fmvAmount: Double?
        set(value): Unit = set(2, value)
        get(): Double? = get(2) as Double?

    open var createdBy: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var totalInr: Double?
        set(value): Unit = set(4, value)
        get(): Double? = get(4) as Double?

    open var updatedOn: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var createdOn: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var staleId: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var noOfHours: Double?
        set(value): Unit = set(8, value)
        get(): Double? = get(8) as Double?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row9<String?, String?, Double?, String?, Double?, OffsetDateTime?, OffsetDateTime?, String?, Double?> = super.fieldsRow() as Row9<String?, String?, Double?, String?, Double?, OffsetDateTime?, OffsetDateTime?, String?, Double?>
    override fun valuesRow(): Row9<String?, String?, Double?, String?, Double?, OffsetDateTime?, OffsetDateTime?, String?, Double?> = super.valuesRow() as Row9<String?, String?, Double?, String?, Double?, OffsetDateTime?, OffsetDateTime?, String?, Double?>
    override fun field1(): Field<String?> = CmeHonoranium.CME_HONORANIUM.ID
    override fun field2(): Field<String?> = CmeHonoranium.CME_HONORANIUM.UPDATED_BY
    override fun field3(): Field<Double?> = CmeHonoranium.CME_HONORANIUM.FMV_AMOUNT
    override fun field4(): Field<String?> = CmeHonoranium.CME_HONORANIUM.CREATED_BY
    override fun field5(): Field<Double?> = CmeHonoranium.CME_HONORANIUM.TOTAL_INR
    override fun field6(): Field<OffsetDateTime?> = CmeHonoranium.CME_HONORANIUM.UPDATED_ON
    override fun field7(): Field<OffsetDateTime?> = CmeHonoranium.CME_HONORANIUM.CREATED_ON
    override fun field8(): Field<String?> = CmeHonoranium.CME_HONORANIUM.STALE_ID
    override fun field9(): Field<Double?> = CmeHonoranium.CME_HONORANIUM.NO_OF_HOURS
    override fun component1(): String? = id
    override fun component2(): String? = updatedBy
    override fun component3(): Double? = fmvAmount
    override fun component4(): String? = createdBy
    override fun component5(): Double? = totalInr
    override fun component6(): OffsetDateTime? = updatedOn
    override fun component7(): OffsetDateTime? = createdOn
    override fun component8(): String? = staleId
    override fun component9(): Double? = noOfHours
    override fun value1(): String? = id
    override fun value2(): String? = updatedBy
    override fun value3(): Double? = fmvAmount
    override fun value4(): String? = createdBy
    override fun value5(): Double? = totalInr
    override fun value6(): OffsetDateTime? = updatedOn
    override fun value7(): OffsetDateTime? = createdOn
    override fun value8(): String? = staleId
    override fun value9(): Double? = noOfHours

    override fun value1(value: String?): CmeHonoraniumRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): CmeHonoraniumRecord {
        this.updatedBy = value
        return this
    }

    override fun value3(value: Double?): CmeHonoraniumRecord {
        this.fmvAmount = value
        return this
    }

    override fun value4(value: String?): CmeHonoraniumRecord {
        this.createdBy = value
        return this
    }

    override fun value5(value: Double?): CmeHonoraniumRecord {
        this.totalInr = value
        return this
    }

    override fun value6(value: OffsetDateTime?): CmeHonoraniumRecord {
        this.updatedOn = value
        return this
    }

    override fun value7(value: OffsetDateTime?): CmeHonoraniumRecord {
        this.createdOn = value
        return this
    }

    override fun value8(value: String?): CmeHonoraniumRecord {
        this.staleId = value
        return this
    }

    override fun value9(value: Double?): CmeHonoraniumRecord {
        this.noOfHours = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: Double?, value4: String?, value5: Double?, value6: OffsetDateTime?, value7: OffsetDateTime?, value8: String?, value9: Double?): CmeHonoraniumRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        return this
    }

    /**
     * Create a detached, initialised CmeHonoraniumRecord
     */
    constructor(id: String? = null, updatedBy: String? = null, fmvAmount: Double? = null, createdBy: String? = null, totalInr: Double? = null, updatedOn: OffsetDateTime? = null, createdOn: OffsetDateTime? = null, staleId: String? = null, noOfHours: Double? = null): this() {
        this.id = id
        this.updatedBy = updatedBy
        this.fmvAmount = fmvAmount
        this.createdBy = createdBy
        this.totalInr = totalInr
        this.updatedOn = updatedOn
        this.createdOn = createdOn
        this.staleId = staleId
        this.noOfHours = noOfHours
    }
}
