/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.CmtEmployeeOld

import java.time.OffsetDateTime

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record14
import org.jooq.Row14
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmtEmployeeOldRecord() : UpdatableRecordImpl<CmtEmployeeOldRecord>(CmtEmployeeOld.CMT_EMPLOYEE_OLD), Record14<OffsetDateTime?, String?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?> {

    open var updatedOn: OffsetDateTime?
        set(value): Unit = set(0, value)
        get(): OffsetDateTime? = get(0) as OffsetDateTime?

    open var jobTitleId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var ciName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdOn: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    open var managerId: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var externalId: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var updatedBy: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var code: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var name: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var staleId: Long?
        set(value): Unit = set(9, value)
        get(): Long? = get(9) as Long?

    open var id: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var locationId: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var statusId: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var createdBy: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row14<OffsetDateTime?, String?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?> = super.fieldsRow() as Row14<OffsetDateTime?, String?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?>
    override fun valuesRow(): Row14<OffsetDateTime?, String?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?> = super.valuesRow() as Row14<OffsetDateTime?, String?, String?, OffsetDateTime?, String?, String?, String?, String?, String?, Long?, String?, String?, String?, String?>
    override fun field1(): Field<OffsetDateTime?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.UPDATED_ON
    override fun field2(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.JOB_TITLE_ID
    override fun field3(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.CI_NAME
    override fun field4(): Field<OffsetDateTime?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.CREATED_ON
    override fun field5(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.MANAGER_ID
    override fun field6(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.EXTERNAL_ID
    override fun field7(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.UPDATED_BY
    override fun field8(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.CODE
    override fun field9(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.NAME
    override fun field10(): Field<Long?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.STALE_ID
    override fun field11(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.ID
    override fun field12(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.LOCATION_ID
    override fun field13(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.STATUS_ID
    override fun field14(): Field<String?> = CmtEmployeeOld.CMT_EMPLOYEE_OLD.CREATED_BY
    override fun component1(): OffsetDateTime? = updatedOn
    override fun component2(): String? = jobTitleId
    override fun component3(): String? = ciName
    override fun component4(): OffsetDateTime? = createdOn
    override fun component5(): String? = managerId
    override fun component6(): String? = externalId
    override fun component7(): String? = updatedBy
    override fun component8(): String? = code
    override fun component9(): String? = name
    override fun component10(): Long? = staleId
    override fun component11(): String? = id
    override fun component12(): String? = locationId
    override fun component13(): String? = statusId
    override fun component14(): String? = createdBy
    override fun value1(): OffsetDateTime? = updatedOn
    override fun value2(): String? = jobTitleId
    override fun value3(): String? = ciName
    override fun value4(): OffsetDateTime? = createdOn
    override fun value5(): String? = managerId
    override fun value6(): String? = externalId
    override fun value7(): String? = updatedBy
    override fun value8(): String? = code
    override fun value9(): String? = name
    override fun value10(): Long? = staleId
    override fun value11(): String? = id
    override fun value12(): String? = locationId
    override fun value13(): String? = statusId
    override fun value14(): String? = createdBy

    override fun value1(value: OffsetDateTime?): CmtEmployeeOldRecord {
        this.updatedOn = value
        return this
    }

    override fun value2(value: String?): CmtEmployeeOldRecord {
        this.jobTitleId = value
        return this
    }

    override fun value3(value: String?): CmtEmployeeOldRecord {
        this.ciName = value
        return this
    }

    override fun value4(value: OffsetDateTime?): CmtEmployeeOldRecord {
        this.createdOn = value
        return this
    }

    override fun value5(value: String?): CmtEmployeeOldRecord {
        this.managerId = value
        return this
    }

    override fun value6(value: String?): CmtEmployeeOldRecord {
        this.externalId = value
        return this
    }

    override fun value7(value: String?): CmtEmployeeOldRecord {
        this.updatedBy = value
        return this
    }

    override fun value8(value: String?): CmtEmployeeOldRecord {
        this.code = value
        return this
    }

    override fun value9(value: String?): CmtEmployeeOldRecord {
        this.name = value
        return this
    }

    override fun value10(value: Long?): CmtEmployeeOldRecord {
        this.staleId = value
        return this
    }

    override fun value11(value: String?): CmtEmployeeOldRecord {
        this.id = value
        return this
    }

    override fun value12(value: String?): CmtEmployeeOldRecord {
        this.locationId = value
        return this
    }

    override fun value13(value: String?): CmtEmployeeOldRecord {
        this.statusId = value
        return this
    }

    override fun value14(value: String?): CmtEmployeeOldRecord {
        this.createdBy = value
        return this
    }

    override fun values(value1: OffsetDateTime?, value2: String?, value3: String?, value4: OffsetDateTime?, value5: String?, value6: String?, value7: String?, value8: String?, value9: String?, value10: Long?, value11: String?, value12: String?, value13: String?, value14: String?): CmtEmployeeOldRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        return this
    }

    /**
     * Create a detached, initialised CmtEmployeeOldRecord
     */
    constructor(updatedOn: OffsetDateTime? = null, jobTitleId: String? = null, ciName: String? = null, createdOn: OffsetDateTime? = null, managerId: String? = null, externalId: String? = null, updatedBy: String? = null, code: String? = null, name: String? = null, staleId: Long? = null, id: String? = null, locationId: String? = null, statusId: String? = null, createdBy: String? = null): this() {
        this.updatedOn = updatedOn
        this.jobTitleId = jobTitleId
        this.ciName = ciName
        this.createdOn = createdOn
        this.managerId = managerId
        this.externalId = externalId
        this.updatedBy = updatedBy
        this.code = code
        this.name = name
        this.staleId = staleId
        this.id = id
        this.locationId = locationId
        this.statusId = statusId
        this.createdBy = createdBy
    }
}
