/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.CmtProduct

import java.time.OffsetDateTime

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record16
import org.jooq.Row16
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmtProductRecord() : UpdatableRecordImpl<CmtProductRecord>(CmtProduct.CMT_PRODUCT), Record16<String?, OffsetDateTime?, String?, OffsetDateTime?, Double?, String?, String?, Boolean?, String?, Long?, String?, String?, String?, String?, String?, String?> {

    open var code: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var updatedOn: OffsetDateTime?
        set(value): Unit = set(1, value)
        get(): OffsetDateTime? = get(1) as OffsetDateTime?

    open var ciName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdOn: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    open var primarySalesPrice: Double?
        set(value): Unit = set(4, value)
        get(): Double? = get(4) as Double?

    open var externalId: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var updatedBy: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsCompetition")
    open var isCompetition: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    open var name: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var staleId: Long?
        set(value): Unit = set(9, value)
        get(): Long? = get(9) as Long?

    open var id: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var ownerId: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var createdBy: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var statusId: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var typeId: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var refName: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row16<String?, OffsetDateTime?, String?, OffsetDateTime?, Double?, String?, String?, Boolean?, String?, Long?, String?, String?, String?, String?, String?, String?> = super.fieldsRow() as Row16<String?, OffsetDateTime?, String?, OffsetDateTime?, Double?, String?, String?, Boolean?, String?, Long?, String?, String?, String?, String?, String?, String?>
    override fun valuesRow(): Row16<String?, OffsetDateTime?, String?, OffsetDateTime?, Double?, String?, String?, Boolean?, String?, Long?, String?, String?, String?, String?, String?, String?> = super.valuesRow() as Row16<String?, OffsetDateTime?, String?, OffsetDateTime?, Double?, String?, String?, Boolean?, String?, Long?, String?, String?, String?, String?, String?, String?>
    override fun field1(): Field<String?> = CmtProduct.CMT_PRODUCT.CODE
    override fun field2(): Field<OffsetDateTime?> = CmtProduct.CMT_PRODUCT.UPDATED_ON
    override fun field3(): Field<String?> = CmtProduct.CMT_PRODUCT.CI_NAME
    override fun field4(): Field<OffsetDateTime?> = CmtProduct.CMT_PRODUCT.CREATED_ON
    override fun field5(): Field<Double?> = CmtProduct.CMT_PRODUCT.PRIMARY_SALES_PRICE
    override fun field6(): Field<String?> = CmtProduct.CMT_PRODUCT.EXTERNAL_ID
    override fun field7(): Field<String?> = CmtProduct.CMT_PRODUCT.UPDATED_BY
    override fun field8(): Field<Boolean?> = CmtProduct.CMT_PRODUCT.IS_COMPETITION
    override fun field9(): Field<String?> = CmtProduct.CMT_PRODUCT.NAME
    override fun field10(): Field<Long?> = CmtProduct.CMT_PRODUCT.STALE_ID
    override fun field11(): Field<String?> = CmtProduct.CMT_PRODUCT.ID
    override fun field12(): Field<String?> = CmtProduct.CMT_PRODUCT.OWNER_ID
    override fun field13(): Field<String?> = CmtProduct.CMT_PRODUCT.CREATED_BY
    override fun field14(): Field<String?> = CmtProduct.CMT_PRODUCT.STATUS_ID
    override fun field15(): Field<String?> = CmtProduct.CMT_PRODUCT.TYPE_ID
    override fun field16(): Field<String?> = CmtProduct.CMT_PRODUCT.REF_NAME
    override fun component1(): String? = code
    override fun component2(): OffsetDateTime? = updatedOn
    override fun component3(): String? = ciName
    override fun component4(): OffsetDateTime? = createdOn
    override fun component5(): Double? = primarySalesPrice
    override fun component6(): String? = externalId
    override fun component7(): String? = updatedBy
    override fun component8(): Boolean? = isCompetition
    override fun component9(): String? = name
    override fun component10(): Long? = staleId
    override fun component11(): String? = id
    override fun component12(): String? = ownerId
    override fun component13(): String? = createdBy
    override fun component14(): String? = statusId
    override fun component15(): String? = typeId
    override fun component16(): String? = refName
    override fun value1(): String? = code
    override fun value2(): OffsetDateTime? = updatedOn
    override fun value3(): String? = ciName
    override fun value4(): OffsetDateTime? = createdOn
    override fun value5(): Double? = primarySalesPrice
    override fun value6(): String? = externalId
    override fun value7(): String? = updatedBy
    override fun value8(): Boolean? = isCompetition
    override fun value9(): String? = name
    override fun value10(): Long? = staleId
    override fun value11(): String? = id
    override fun value12(): String? = ownerId
    override fun value13(): String? = createdBy
    override fun value14(): String? = statusId
    override fun value15(): String? = typeId
    override fun value16(): String? = refName

    override fun value1(value: String?): CmtProductRecord {
        this.code = value
        return this
    }

    override fun value2(value: OffsetDateTime?): CmtProductRecord {
        this.updatedOn = value
        return this
    }

    override fun value3(value: String?): CmtProductRecord {
        this.ciName = value
        return this
    }

    override fun value4(value: OffsetDateTime?): CmtProductRecord {
        this.createdOn = value
        return this
    }

    override fun value5(value: Double?): CmtProductRecord {
        this.primarySalesPrice = value
        return this
    }

    override fun value6(value: String?): CmtProductRecord {
        this.externalId = value
        return this
    }

    override fun value7(value: String?): CmtProductRecord {
        this.updatedBy = value
        return this
    }

    override fun value8(value: Boolean?): CmtProductRecord {
        this.isCompetition = value
        return this
    }

    override fun value9(value: String?): CmtProductRecord {
        this.name = value
        return this
    }

    override fun value10(value: Long?): CmtProductRecord {
        this.staleId = value
        return this
    }

    override fun value11(value: String?): CmtProductRecord {
        this.id = value
        return this
    }

    override fun value12(value: String?): CmtProductRecord {
        this.ownerId = value
        return this
    }

    override fun value13(value: String?): CmtProductRecord {
        this.createdBy = value
        return this
    }

    override fun value14(value: String?): CmtProductRecord {
        this.statusId = value
        return this
    }

    override fun value15(value: String?): CmtProductRecord {
        this.typeId = value
        return this
    }

    override fun value16(value: String?): CmtProductRecord {
        this.refName = value
        return this
    }

    override fun values(value1: String?, value2: OffsetDateTime?, value3: String?, value4: OffsetDateTime?, value5: Double?, value6: String?, value7: String?, value8: Boolean?, value9: String?, value10: Long?, value11: String?, value12: String?, value13: String?, value14: String?, value15: String?, value16: String?): CmtProductRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        this.value16(value16)
        return this
    }

    /**
     * Create a detached, initialised CmtProductRecord
     */
    constructor(code: String? = null, updatedOn: OffsetDateTime? = null, ciName: String? = null, createdOn: OffsetDateTime? = null, primarySalesPrice: Double? = null, externalId: String? = null, updatedBy: String? = null, isCompetition: Boolean? = null, name: String? = null, staleId: Long? = null, id: String? = null, ownerId: String? = null, createdBy: String? = null, statusId: String? = null, typeId: String? = null, refName: String? = null): this() {
        this.code = code
        this.updatedOn = updatedOn
        this.ciName = ciName
        this.createdOn = createdOn
        this.primarySalesPrice = primarySalesPrice
        this.externalId = externalId
        this.updatedBy = updatedBy
        this.isCompetition = isCompetition
        this.name = name
        this.staleId = staleId
        this.id = id
        this.ownerId = ownerId
        this.createdBy = createdBy
        this.statusId = statusId
        this.typeId = typeId
        this.refName = refName
    }
}
