/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.CmtRetailer

import java.time.OffsetDateTime

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record12
import org.jooq.Row12
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class CmtRetailerRecord() : UpdatableRecordImpl<CmtRetailerRecord>(CmtRetailer.CMT_RETAILER), Record12<String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?> {

    open var name: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var statusId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var updatedOn: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    open var locationId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var staleId: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open var ciName: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdOn: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var externalId: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var id: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var updatedBy: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var code: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var createdBy: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row12<String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?> = super.fieldsRow() as Row12<String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?>
    override fun valuesRow(): Row12<String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?> = super.valuesRow() as Row12<String?, String?, OffsetDateTime?, String?, Long?, String?, OffsetDateTime?, String?, String?, String?, String?, String?>
    override fun field1(): Field<String?> = CmtRetailer.CMT_RETAILER.NAME
    override fun field2(): Field<String?> = CmtRetailer.CMT_RETAILER.STATUS_ID
    override fun field3(): Field<OffsetDateTime?> = CmtRetailer.CMT_RETAILER.UPDATED_ON
    override fun field4(): Field<String?> = CmtRetailer.CMT_RETAILER.LOCATION_ID
    override fun field5(): Field<Long?> = CmtRetailer.CMT_RETAILER.STALE_ID
    override fun field6(): Field<String?> = CmtRetailer.CMT_RETAILER.CI_NAME
    override fun field7(): Field<OffsetDateTime?> = CmtRetailer.CMT_RETAILER.CREATED_ON
    override fun field8(): Field<String?> = CmtRetailer.CMT_RETAILER.EXTERNAL_ID
    override fun field9(): Field<String?> = CmtRetailer.CMT_RETAILER.ID
    override fun field10(): Field<String?> = CmtRetailer.CMT_RETAILER.UPDATED_BY
    override fun field11(): Field<String?> = CmtRetailer.CMT_RETAILER.CODE
    override fun field12(): Field<String?> = CmtRetailer.CMT_RETAILER.CREATED_BY
    override fun component1(): String? = name
    override fun component2(): String? = statusId
    override fun component3(): OffsetDateTime? = updatedOn
    override fun component4(): String? = locationId
    override fun component5(): Long? = staleId
    override fun component6(): String? = ciName
    override fun component7(): OffsetDateTime? = createdOn
    override fun component8(): String? = externalId
    override fun component9(): String? = id
    override fun component10(): String? = updatedBy
    override fun component11(): String? = code
    override fun component12(): String? = createdBy
    override fun value1(): String? = name
    override fun value2(): String? = statusId
    override fun value3(): OffsetDateTime? = updatedOn
    override fun value4(): String? = locationId
    override fun value5(): Long? = staleId
    override fun value6(): String? = ciName
    override fun value7(): OffsetDateTime? = createdOn
    override fun value8(): String? = externalId
    override fun value9(): String? = id
    override fun value10(): String? = updatedBy
    override fun value11(): String? = code
    override fun value12(): String? = createdBy

    override fun value1(value: String?): CmtRetailerRecord {
        this.name = value
        return this
    }

    override fun value2(value: String?): CmtRetailerRecord {
        this.statusId = value
        return this
    }

    override fun value3(value: OffsetDateTime?): CmtRetailerRecord {
        this.updatedOn = value
        return this
    }

    override fun value4(value: String?): CmtRetailerRecord {
        this.locationId = value
        return this
    }

    override fun value5(value: Long?): CmtRetailerRecord {
        this.staleId = value
        return this
    }

    override fun value6(value: String?): CmtRetailerRecord {
        this.ciName = value
        return this
    }

    override fun value7(value: OffsetDateTime?): CmtRetailerRecord {
        this.createdOn = value
        return this
    }

    override fun value8(value: String?): CmtRetailerRecord {
        this.externalId = value
        return this
    }

    override fun value9(value: String?): CmtRetailerRecord {
        this.id = value
        return this
    }

    override fun value10(value: String?): CmtRetailerRecord {
        this.updatedBy = value
        return this
    }

    override fun value11(value: String?): CmtRetailerRecord {
        this.code = value
        return this
    }

    override fun value12(value: String?): CmtRetailerRecord {
        this.createdBy = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: OffsetDateTime?, value4: String?, value5: Long?, value6: String?, value7: OffsetDateTime?, value8: String?, value9: String?, value10: String?, value11: String?, value12: String?): CmtRetailerRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        return this
    }

    /**
     * Create a detached, initialised CmtRetailerRecord
     */
    constructor(name: String? = null, statusId: String? = null, updatedOn: OffsetDateTime? = null, locationId: String? = null, staleId: Long? = null, ciName: String? = null, createdOn: OffsetDateTime? = null, externalId: String? = null, id: String? = null, updatedBy: String? = null, code: String? = null, createdBy: String? = null): this() {
        this.name = name
        this.statusId = statusId
        this.updatedOn = updatedOn
        this.locationId = locationId
        this.staleId = staleId
        this.ciName = ciName
        this.createdOn = createdOn
        this.externalId = externalId
        this.id = id
        this.updatedBy = updatedBy
        this.code = code
        this.createdBy = createdBy
    }
}
