/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.DshConsolidatedLocationPrimarySales

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshConsolidatedLocationPrimarySalesRecord() : TableRecordImpl<DshConsolidatedLocationPrimarySalesRecord>(DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES), Record10<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?> {

    open var divisionId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var locationId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var month: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var year: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var yearmonth: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var targetValue: Double?
        set(value): Unit = set(5, value)
        get(): Double? = get(5) as Double?

    open var targetQuantity: Double?
        set(value): Unit = set(6, value)
        get(): Double? = get(6) as Double?

    open var achivementValue: Double?
        set(value): Unit = set(7, value)
        get(): Double? = get(7) as Double?

    open var achievementQuantity: Double?
        set(value): Unit = set(8, value)
        get(): Double? = get(8) as Double?

    open var pendingValue: Double?
        set(value): Unit = set(9, value)
        get(): Double? = get(9) as Double?

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row10<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?> = super.fieldsRow() as Row10<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?>
    override fun valuesRow(): Row10<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?> = super.valuesRow() as Row10<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Double?>
    override fun field1(): Field<String?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.DIVISION_ID
    override fun field2(): Field<String?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.LOCATION_ID
    override fun field3(): Field<Int?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.MONTH
    override fun field4(): Field<Int?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.YEAR
    override fun field5(): Field<Int?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.YEARMONTH
    override fun field6(): Field<Double?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.TARGET_VALUE
    override fun field7(): Field<Double?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.TARGET_QUANTITY
    override fun field8(): Field<Double?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.ACHIVEMENT_VALUE
    override fun field9(): Field<Double?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.ACHIEVEMENT_QUANTITY
    override fun field10(): Field<Double?> = DshConsolidatedLocationPrimarySales.DSH_CONSOLIDATED_LOCATION_PRIMARY_SALES.PENDING_VALUE
    override fun component1(): String? = divisionId
    override fun component2(): String? = locationId
    override fun component3(): Int? = month
    override fun component4(): Int? = year
    override fun component5(): Int? = yearmonth
    override fun component6(): Double? = targetValue
    override fun component7(): Double? = targetQuantity
    override fun component8(): Double? = achivementValue
    override fun component9(): Double? = achievementQuantity
    override fun component10(): Double? = pendingValue
    override fun value1(): String? = divisionId
    override fun value2(): String? = locationId
    override fun value3(): Int? = month
    override fun value4(): Int? = year
    override fun value5(): Int? = yearmonth
    override fun value6(): Double? = targetValue
    override fun value7(): Double? = targetQuantity
    override fun value8(): Double? = achivementValue
    override fun value9(): Double? = achievementQuantity
    override fun value10(): Double? = pendingValue

    override fun value1(value: String?): DshConsolidatedLocationPrimarySalesRecord {
        this.divisionId = value
        return this
    }

    override fun value2(value: String?): DshConsolidatedLocationPrimarySalesRecord {
        this.locationId = value
        return this
    }

    override fun value3(value: Int?): DshConsolidatedLocationPrimarySalesRecord {
        this.month = value
        return this
    }

    override fun value4(value: Int?): DshConsolidatedLocationPrimarySalesRecord {
        this.year = value
        return this
    }

    override fun value5(value: Int?): DshConsolidatedLocationPrimarySalesRecord {
        this.yearmonth = value
        return this
    }

    override fun value6(value: Double?): DshConsolidatedLocationPrimarySalesRecord {
        this.targetValue = value
        return this
    }

    override fun value7(value: Double?): DshConsolidatedLocationPrimarySalesRecord {
        this.targetQuantity = value
        return this
    }

    override fun value8(value: Double?): DshConsolidatedLocationPrimarySalesRecord {
        this.achivementValue = value
        return this
    }

    override fun value9(value: Double?): DshConsolidatedLocationPrimarySalesRecord {
        this.achievementQuantity = value
        return this
    }

    override fun value10(value: Double?): DshConsolidatedLocationPrimarySalesRecord {
        this.pendingValue = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: Int?, value4: Int?, value5: Int?, value6: Double?, value7: Double?, value8: Double?, value9: Double?, value10: Double?): DshConsolidatedLocationPrimarySalesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    /**
     * Create a detached, initialised DshConsolidatedLocationPrimarySalesRecord
     */
    constructor(divisionId: String? = null, locationId: String? = null, month: Int? = null, year: Int? = null, yearmonth: Int? = null, targetValue: Double? = null, targetQuantity: Double? = null, achivementValue: Double? = null, achievementQuantity: Double? = null, pendingValue: Double? = null): this() {
        this.divisionId = divisionId
        this.locationId = locationId
        this.month = month
        this.year = year
        this.yearmonth = yearmonth
        this.targetValue = targetValue
        this.targetQuantity = targetQuantity
        this.achivementValue = achivementValue
        this.achievementQuantity = achievementQuantity
        this.pendingValue = pendingValue
    }
}
