/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.DshConsolidatedLocationBrandSecondarySales

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshConsolidatedLocationBrandSecondarySalesRecord() : TableRecordImpl<DshConsolidatedLocationBrandSecondarySalesRecord>(DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES), Record10<String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?> {

    open var divisionId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var locationId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var brandId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var month: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var year: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var yearmonth: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var secondaryUnits: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var closingUnits: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var secondaryValue: Double?
        set(value): Unit = set(8, value)
        get(): Double? = get(8) as Double?

    open var closingValue: Double?
        set(value): Unit = set(9, value)
        get(): Double? = get(9) as Double?

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row10<String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?> = super.fieldsRow() as Row10<String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?>
    override fun valuesRow(): Row10<String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?> = super.valuesRow() as Row10<String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Double?, Double?>
    override fun field1(): Field<String?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.DIVISION_ID
    override fun field2(): Field<String?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.LOCATION_ID
    override fun field3(): Field<String?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.BRAND_ID
    override fun field4(): Field<Int?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.MONTH
    override fun field5(): Field<Int?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.YEAR
    override fun field6(): Field<Int?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.YEARMONTH
    override fun field7(): Field<Int?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.SECONDARY_UNITS
    override fun field8(): Field<Int?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.CLOSING_UNITS
    override fun field9(): Field<Double?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.SECONDARY_VALUE
    override fun field10(): Field<Double?> = DshConsolidatedLocationBrandSecondarySales.DSH_CONSOLIDATED_LOCATION_BRAND_SECONDARY_SALES.CLOSING_VALUE
    override fun component1(): String? = divisionId
    override fun component2(): String? = locationId
    override fun component3(): String? = brandId
    override fun component4(): Int? = month
    override fun component5(): Int? = year
    override fun component6(): Int? = yearmonth
    override fun component7(): Int? = secondaryUnits
    override fun component8(): Int? = closingUnits
    override fun component9(): Double? = secondaryValue
    override fun component10(): Double? = closingValue
    override fun value1(): String? = divisionId
    override fun value2(): String? = locationId
    override fun value3(): String? = brandId
    override fun value4(): Int? = month
    override fun value5(): Int? = year
    override fun value6(): Int? = yearmonth
    override fun value7(): Int? = secondaryUnits
    override fun value8(): Int? = closingUnits
    override fun value9(): Double? = secondaryValue
    override fun value10(): Double? = closingValue

    override fun value1(value: String?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.divisionId = value
        return this
    }

    override fun value2(value: String?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.locationId = value
        return this
    }

    override fun value3(value: String?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.brandId = value
        return this
    }

    override fun value4(value: Int?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.month = value
        return this
    }

    override fun value5(value: Int?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.year = value
        return this
    }

    override fun value6(value: Int?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.yearmonth = value
        return this
    }

    override fun value7(value: Int?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.secondaryUnits = value
        return this
    }

    override fun value8(value: Int?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.closingUnits = value
        return this
    }

    override fun value9(value: Double?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.secondaryValue = value
        return this
    }

    override fun value10(value: Double?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.closingValue = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: Int?, value5: Int?, value6: Int?, value7: Int?, value8: Int?, value9: Double?, value10: Double?): DshConsolidatedLocationBrandSecondarySalesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    /**
     * Create a detached, initialised
     * DshConsolidatedLocationBrandSecondarySalesRecord
     */
    constructor(divisionId: String? = null, locationId: String? = null, brandId: String? = null, month: Int? = null, year: Int? = null, yearmonth: Int? = null, secondaryUnits: Int? = null, closingUnits: Int? = null, secondaryValue: Double? = null, closingValue: Double? = null): this() {
        this.divisionId = divisionId
        this.locationId = locationId
        this.brandId = brandId
        this.month = month
        this.year = year
        this.yearmonth = yearmonth
        this.secondaryUnits = secondaryUnits
        this.closingUnits = closingUnits
        this.secondaryValue = secondaryValue
        this.closingValue = closingValue
    }
}
