/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.DshConsolidatedLocationFrequency

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record16
import org.jooq.Row16
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshConsolidatedLocationFrequencyRecord() : TableRecordImpl<DshConsolidatedLocationFrequencyRecord>(DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY), Record16<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Double?, Int?, Int?, Int?> {

    open var divisionId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var locationId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var month: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var year: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var yearmonth: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var aFrequency: Double?
        set(value): Unit = set(5, value)
        get(): Double? = get(5) as Double?

    open var bFrequency: Double?
        set(value): Unit = set(6, value)
        get(): Double? = get(6) as Double?

    open var cFrequency: Double?
        set(value): Unit = set(7, value)
        get(): Double? = get(7) as Double?

    open var callAverage: Double?
        set(value): Unit = set(8, value)
        get(): Double? = get(8) as Double?

    open var fieldDays: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    open var totalDoctors: Int?
        set(value): Unit = set(10, value)
        get(): Int? = get(10) as Int?

    open var totalDoctorVisit: Int?
        set(value): Unit = set(11, value)
        get(): Int? = get(11) as Int?

    open var totalFrequency: Double?
        set(value): Unit = set(12, value)
        get(): Double? = get(12) as Double?

    open var aFrequencyMet: Int?
        set(value): Unit = set(13, value)
        get(): Int? = get(13) as Int?

    open var bFrequencyMet: Int?
        set(value): Unit = set(14, value)
        get(): Int? = get(14) as Int?

    open var cFrequencyMet: Int?
        set(value): Unit = set(15, value)
        get(): Int? = get(15) as Int?

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row16<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Double?, Int?, Int?, Int?> = super.fieldsRow() as Row16<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Double?, Int?, Int?, Int?>
    override fun valuesRow(): Row16<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Double?, Int?, Int?, Int?> = super.valuesRow() as Row16<String?, String?, Int?, Int?, Int?, Double?, Double?, Double?, Double?, Int?, Int?, Int?, Double?, Int?, Int?, Int?>
    override fun field1(): Field<String?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.DIVISION_ID
    override fun field2(): Field<String?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.LOCATION_ID
    override fun field3(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.MONTH
    override fun field4(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.YEAR
    override fun field5(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.YEARMONTH
    override fun field6(): Field<Double?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.A_FREQUENCY
    override fun field7(): Field<Double?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.B_FREQUENCY
    override fun field8(): Field<Double?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.C_FREQUENCY
    override fun field9(): Field<Double?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.CALL_AVERAGE
    override fun field10(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.FIELD_DAYS
    override fun field11(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.TOTAL_DOCTORS
    override fun field12(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.TOTAL_DOCTOR_VISIT
    override fun field13(): Field<Double?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.TOTAL_FREQUENCY
    override fun field14(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.A_FREQUENCY_MET
    override fun field15(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.B_FREQUENCY_MET
    override fun field16(): Field<Int?> = DshConsolidatedLocationFrequency.DSH_CONSOLIDATED_LOCATION_FREQUENCY.C_FREQUENCY_MET
    override fun component1(): String? = divisionId
    override fun component2(): String? = locationId
    override fun component3(): Int? = month
    override fun component4(): Int? = year
    override fun component5(): Int? = yearmonth
    override fun component6(): Double? = aFrequency
    override fun component7(): Double? = bFrequency
    override fun component8(): Double? = cFrequency
    override fun component9(): Double? = callAverage
    override fun component10(): Int? = fieldDays
    override fun component11(): Int? = totalDoctors
    override fun component12(): Int? = totalDoctorVisit
    override fun component13(): Double? = totalFrequency
    override fun component14(): Int? = aFrequencyMet
    override fun component15(): Int? = bFrequencyMet
    override fun component16(): Int? = cFrequencyMet
    override fun value1(): String? = divisionId
    override fun value2(): String? = locationId
    override fun value3(): Int? = month
    override fun value4(): Int? = year
    override fun value5(): Int? = yearmonth
    override fun value6(): Double? = aFrequency
    override fun value7(): Double? = bFrequency
    override fun value8(): Double? = cFrequency
    override fun value9(): Double? = callAverage
    override fun value10(): Int? = fieldDays
    override fun value11(): Int? = totalDoctors
    override fun value12(): Int? = totalDoctorVisit
    override fun value13(): Double? = totalFrequency
    override fun value14(): Int? = aFrequencyMet
    override fun value15(): Int? = bFrequencyMet
    override fun value16(): Int? = cFrequencyMet

    override fun value1(value: String?): DshConsolidatedLocationFrequencyRecord {
        this.divisionId = value
        return this
    }

    override fun value2(value: String?): DshConsolidatedLocationFrequencyRecord {
        this.locationId = value
        return this
    }

    override fun value3(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.month = value
        return this
    }

    override fun value4(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.year = value
        return this
    }

    override fun value5(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.yearmonth = value
        return this
    }

    override fun value6(value: Double?): DshConsolidatedLocationFrequencyRecord {
        this.aFrequency = value
        return this
    }

    override fun value7(value: Double?): DshConsolidatedLocationFrequencyRecord {
        this.bFrequency = value
        return this
    }

    override fun value8(value: Double?): DshConsolidatedLocationFrequencyRecord {
        this.cFrequency = value
        return this
    }

    override fun value9(value: Double?): DshConsolidatedLocationFrequencyRecord {
        this.callAverage = value
        return this
    }

    override fun value10(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.fieldDays = value
        return this
    }

    override fun value11(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.totalDoctors = value
        return this
    }

    override fun value12(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.totalDoctorVisit = value
        return this
    }

    override fun value13(value: Double?): DshConsolidatedLocationFrequencyRecord {
        this.totalFrequency = value
        return this
    }

    override fun value14(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.aFrequencyMet = value
        return this
    }

    override fun value15(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.bFrequencyMet = value
        return this
    }

    override fun value16(value: Int?): DshConsolidatedLocationFrequencyRecord {
        this.cFrequencyMet = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: Int?, value4: Int?, value5: Int?, value6: Double?, value7: Double?, value8: Double?, value9: Double?, value10: Int?, value11: Int?, value12: Int?, value13: Double?, value14: Int?, value15: Int?, value16: Int?): DshConsolidatedLocationFrequencyRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        this.value16(value16)
        return this
    }

    /**
     * Create a detached, initialised DshConsolidatedLocationFrequencyRecord
     */
    constructor(divisionId: String? = null, locationId: String? = null, month: Int? = null, year: Int? = null, yearmonth: Int? = null, aFrequency: Double? = null, bFrequency: Double? = null, cFrequency: Double? = null, callAverage: Double? = null, fieldDays: Int? = null, totalDoctors: Int? = null, totalDoctorVisit: Int? = null, totalFrequency: Double? = null, aFrequencyMet: Int? = null, bFrequencyMet: Int? = null, cFrequencyMet: Int? = null): this() {
        this.divisionId = divisionId
        this.locationId = locationId
        this.month = month
        this.year = year
        this.yearmonth = yearmonth
        this.aFrequency = aFrequency
        this.bFrequency = bFrequency
        this.cFrequency = cFrequency
        this.callAverage = callAverage
        this.fieldDays = fieldDays
        this.totalDoctors = totalDoctors
        this.totalDoctorVisit = totalDoctorVisit
        this.totalFrequency = totalFrequency
        this.aFrequencyMet = aFrequencyMet
        this.bFrequencyMet = bFrequencyMet
        this.cFrequencyMet = cFrequencyMet
    }
}
