/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.DshLocationwiseConsolidatedRetailerProductAvailability

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshLocationwiseConsolidatedRetailerProductAvailabilityRecord() : TableRecordImpl<DshLocationwiseConsolidatedRetailerProductAvailabilityRecord>(DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY), Record8<String?, String?, String?, Int?, Int?, Int?, Int?, Int?> {

    open var divisionId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var locationId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var brandId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var month: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var year: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var yearmonth: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var total: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var retailers: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<String?, String?, String?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row8<String?, String?, String?, Int?, Int?, Int?, Int?, Int?>
    override fun valuesRow(): Row8<String?, String?, String?, Int?, Int?, Int?, Int?, Int?> = super.valuesRow() as Row8<String?, String?, String?, Int?, Int?, Int?, Int?, Int?>
    override fun field1(): Field<String?> = DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY.DIVISION_ID
    override fun field2(): Field<String?> = DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY.LOCATION_ID
    override fun field3(): Field<String?> = DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY.BRAND_ID
    override fun field4(): Field<Int?> = DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY.MONTH
    override fun field5(): Field<Int?> = DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY.YEAR
    override fun field6(): Field<Int?> = DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY.YEARMONTH
    override fun field7(): Field<Int?> = DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY.TOTAL
    override fun field8(): Field<Int?> = DshLocationwiseConsolidatedRetailerProductAvailability.DSH_LOCATIONWISE_CONSOLIDATED_RETAILER_PRODUCT_AVAILABILITY.RETAILERS
    override fun component1(): String? = divisionId
    override fun component2(): String? = locationId
    override fun component3(): String? = brandId
    override fun component4(): Int? = month
    override fun component5(): Int? = year
    override fun component6(): Int? = yearmonth
    override fun component7(): Int? = total
    override fun component8(): Int? = retailers
    override fun value1(): String? = divisionId
    override fun value2(): String? = locationId
    override fun value3(): String? = brandId
    override fun value4(): Int? = month
    override fun value5(): Int? = year
    override fun value6(): Int? = yearmonth
    override fun value7(): Int? = total
    override fun value8(): Int? = retailers

    override fun value1(value: String?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.divisionId = value
        return this
    }

    override fun value2(value: String?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.locationId = value
        return this
    }

    override fun value3(value: String?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.brandId = value
        return this
    }

    override fun value4(value: Int?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.month = value
        return this
    }

    override fun value5(value: Int?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.year = value
        return this
    }

    override fun value6(value: Int?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.yearmonth = value
        return this
    }

    override fun value7(value: Int?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.total = value
        return this
    }

    override fun value8(value: Int?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.retailers = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: Int?, value5: Int?, value6: Int?, value7: Int?, value8: Int?): DshLocationwiseConsolidatedRetailerProductAvailabilityRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised
     * DshLocationwiseConsolidatedRetailerProductAvailabilityRecord
     */
    constructor(divisionId: String? = null, locationId: String? = null, brandId: String? = null, month: Int? = null, year: Int? = null, yearmonth: Int? = null, total: Int? = null, retailers: Int? = null): this() {
        this.divisionId = divisionId
        this.locationId = locationId
        this.brandId = brandId
        this.month = month
        this.year = year
        this.yearmonth = yearmonth
        this.total = total
        this.retailers = retailers
    }
}
