/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.DshMonthlyConsolidatedLocationwiseAvailability

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class DshMonthlyConsolidatedLocationwiseAvailabilityRecord() : TableRecordImpl<DshMonthlyConsolidatedLocationwiseAvailabilityRecord>(DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY), Record10<String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> {

    open var divisionId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var locationId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var availability_1: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var availability_2: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var availability_3: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var availability_4: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var month: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var year: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var yearmonth: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var availability_5: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row10<String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row10<String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>
    override fun valuesRow(): Row10<String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.valuesRow() as Row10<String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>
    override fun field1(): Field<String?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.DIVISION_ID
    override fun field2(): Field<String?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.LOCATION_ID
    override fun field3(): Field<Int?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.AVAILABILITY_1
    override fun field4(): Field<Int?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.AVAILABILITY_2
    override fun field5(): Field<Int?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.AVAILABILITY_3
    override fun field6(): Field<Int?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.AVAILABILITY_4
    override fun field7(): Field<Int?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.MONTH
    override fun field8(): Field<Int?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.YEAR
    override fun field9(): Field<Int?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.YEARMONTH
    override fun field10(): Field<Int?> = DshMonthlyConsolidatedLocationwiseAvailability.DSH_MONTHLY_CONSOLIDATED_LOCATIONWISE_AVAILABILITY.AVAILABILITY_5
    override fun component1(): String? = divisionId
    override fun component2(): String? = locationId
    override fun component3(): Int? = availability_1
    override fun component4(): Int? = availability_2
    override fun component5(): Int? = availability_3
    override fun component6(): Int? = availability_4
    override fun component7(): Int? = month
    override fun component8(): Int? = year
    override fun component9(): Int? = yearmonth
    override fun component10(): Int? = availability_5
    override fun value1(): String? = divisionId
    override fun value2(): String? = locationId
    override fun value3(): Int? = availability_1
    override fun value4(): Int? = availability_2
    override fun value5(): Int? = availability_3
    override fun value6(): Int? = availability_4
    override fun value7(): Int? = month
    override fun value8(): Int? = year
    override fun value9(): Int? = yearmonth
    override fun value10(): Int? = availability_5

    override fun value1(value: String?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.divisionId = value
        return this
    }

    override fun value2(value: String?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.locationId = value
        return this
    }

    override fun value3(value: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.availability_1 = value
        return this
    }

    override fun value4(value: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.availability_2 = value
        return this
    }

    override fun value5(value: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.availability_3 = value
        return this
    }

    override fun value6(value: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.availability_4 = value
        return this
    }

    override fun value7(value: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.month = value
        return this
    }

    override fun value8(value: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.year = value
        return this
    }

    override fun value9(value: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.yearmonth = value
        return this
    }

    override fun value10(value: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.availability_5 = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: Int?, value4: Int?, value5: Int?, value6: Int?, value7: Int?, value8: Int?, value9: Int?, value10: Int?): DshMonthlyConsolidatedLocationwiseAvailabilityRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    /**
     * Create a detached, initialised
     * DshMonthlyConsolidatedLocationwiseAvailabilityRecord
     */
    constructor(divisionId: String? = null, locationId: String? = null, availability_1: Int? = null, availability_2: Int? = null, availability_3: Int? = null, availability_4: Int? = null, month: Int? = null, year: Int? = null, yearmonth: Int? = null, availability_5: Int? = null): this() {
        this.divisionId = divisionId
        this.locationId = locationId
        this.availability_1 = availability_1
        this.availability_2 = availability_2
        this.availability_3 = availability_3
        this.availability_4 = availability_4
        this.month = month
        this.year = year
        this.yearmonth = yearmonth
        this.availability_5 = availability_5
    }
}
