/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.RptMonthlyConsolidatedActivity

import javax.annotation.processing.Generated

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class RptMonthlyConsolidatedActivityRecord() : TableRecordImpl<RptMonthlyConsolidatedActivityRecord>(RptMonthlyConsolidatedActivity.RPT_MONTHLY_CONSOLIDATED_ACTIVITY) {

    open var locationId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var totalDoctors: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var totalDoctorsVisited: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var totalClassaVisited: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var totalClassbVisited: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var totalClasscVisited: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var fieldDays: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var callAverage: Double?
        set(value): Unit = set(7, value)
        get(): Double? = get(7) as Double?

    open var classaCallAverage: Double?
        set(value): Unit = set(8, value)
        get(): Double? = get(8) as Double?

    open var classbCallAverage: Double?
        set(value): Unit = set(9, value)
        get(): Double? = get(9) as Double?

    open var classcCallAverage: Double?
        set(value): Unit = set(10, value)
        get(): Double? = get(10) as Double?

    open var distinctDoctorVisits: Int?
        set(value): Unit = set(11, value)
        get(): Int? = get(11) as Int?

    open var classaCoverage: Double?
        set(value): Unit = set(12, value)
        get(): Double? = get(12) as Double?

    open var classbCoverage: Double?
        set(value): Unit = set(13, value)
        get(): Double? = get(13) as Double?

    open var classcCoverage: Double?
        set(value): Unit = set(14, value)
        get(): Double? = get(14) as Double?

    open var classaFrequency: Double?
        set(value): Unit = set(15, value)
        get(): Double? = get(15) as Double?

    open var classbFrequency: Double?
        set(value): Unit = set(16, value)
        get(): Double? = get(16) as Double?

    open var classcFrequency: Double?
        set(value): Unit = set(17, value)
        get(): Double? = get(17) as Double?

    open var totalCoverage: Double?
        set(value): Unit = set(18, value)
        get(): Double? = get(18) as Double?

    open var month: Int?
        set(value): Unit = set(19, value)
        get(): Int? = get(19) as Int?

    open var year: Int?
        set(value): Unit = set(20, value)
        get(): Int? = get(20) as Int?

    open var yearmonth: Int?
        set(value): Unit = set(21, value)
        get(): Int? = get(21) as Int?

    open var totalClassaDoctors: Int?
        set(value): Unit = set(22, value)
        get(): Int? = get(22) as Int?

    open var totalClassbDoctors: Int?
        set(value): Unit = set(23, value)
        get(): Int? = get(23) as Int?

    open var totalClasscDoctors: Int?
        set(value): Unit = set(24, value)
        get(): Int? = get(24) as Int?

    open var totalDistinctClassaVisited: Int?
        set(value): Unit = set(25, value)
        get(): Int? = get(25) as Int?

    open var totalDistinctClassbVisited: Int?
        set(value): Unit = set(26, value)
        get(): Int? = get(26) as Int?

    open var totalDistinctClasscVisited: Int?
        set(value): Unit = set(27, value)
        get(): Int? = get(27) as Int?

    open var totalFrequency: Double?
        set(value): Unit = set(28, value)
        get(): Double? = get(28) as Double?

    /**
     * Create a detached, initialised RptMonthlyConsolidatedActivityRecord
     */
    constructor(locationId: String? = null, totalDoctors: Int? = null, totalDoctorsVisited: Int? = null, totalClassaVisited: Int? = null, totalClassbVisited: Int? = null, totalClasscVisited: Int? = null, fieldDays: Int? = null, callAverage: Double? = null, classaCallAverage: Double? = null, classbCallAverage: Double? = null, classcCallAverage: Double? = null, distinctDoctorVisits: Int? = null, classaCoverage: Double? = null, classbCoverage: Double? = null, classcCoverage: Double? = null, classaFrequency: Double? = null, classbFrequency: Double? = null, classcFrequency: Double? = null, totalCoverage: Double? = null, month: Int? = null, year: Int? = null, yearmonth: Int? = null, totalClassaDoctors: Int? = null, totalClassbDoctors: Int? = null, totalClasscDoctors: Int? = null, totalDistinctClassaVisited: Int? = null, totalDistinctClassbVisited: Int? = null, totalDistinctClasscVisited: Int? = null, totalFrequency: Double? = null): this() {
        this.locationId = locationId
        this.totalDoctors = totalDoctors
        this.totalDoctorsVisited = totalDoctorsVisited
        this.totalClassaVisited = totalClassaVisited
        this.totalClassbVisited = totalClassbVisited
        this.totalClasscVisited = totalClasscVisited
        this.fieldDays = fieldDays
        this.callAverage = callAverage
        this.classaCallAverage = classaCallAverage
        this.classbCallAverage = classbCallAverage
        this.classcCallAverage = classcCallAverage
        this.distinctDoctorVisits = distinctDoctorVisits
        this.classaCoverage = classaCoverage
        this.classbCoverage = classbCoverage
        this.classcCoverage = classcCoverage
        this.classaFrequency = classaFrequency
        this.classbFrequency = classbFrequency
        this.classcFrequency = classcFrequency
        this.totalCoverage = totalCoverage
        this.month = month
        this.year = year
        this.yearmonth = yearmonth
        this.totalClassaDoctors = totalClassaDoctors
        this.totalClassbDoctors = totalClassbDoctors
        this.totalClasscDoctors = totalClasscDoctors
        this.totalDistinctClassaVisited = totalDistinctClassaVisited
        this.totalDistinctClassbVisited = totalDistinctClassbVisited
        this.totalDistinctClasscVisited = totalDistinctClasscVisited
        this.totalFrequency = totalFrequency
    }
}
