/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.Securityroleprivilege

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class SecurityroleprivilegeRecord() : TableRecordImpl<SecurityroleprivilegeRecord>(Securityroleprivilege.SECURITYROLEPRIVILEGE), Record2<Long?, Long?> {

    open var roleId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var privilegeId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<Long?, Long?> = super.fieldsRow() as Row2<Long?, Long?>
    override fun valuesRow(): Row2<Long?, Long?> = super.valuesRow() as Row2<Long?, Long?>
    override fun field1(): Field<Long?> = Securityroleprivilege.SECURITYROLEPRIVILEGE.ROLE_ID
    override fun field2(): Field<Long?> = Securityroleprivilege.SECURITYROLEPRIVILEGE.PRIVILEGE_ID
    override fun component1(): Long? = roleId
    override fun component2(): Long? = privilegeId
    override fun value1(): Long? = roleId
    override fun value2(): Long? = privilegeId

    override fun value1(value: Long?): SecurityroleprivilegeRecord {
        this.roleId = value
        return this
    }

    override fun value2(value: Long?): SecurityroleprivilegeRecord {
        this.privilegeId = value
        return this
    }

    override fun values(value1: Long?, value2: Long?): SecurityroleprivilegeRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    /**
     * Create a detached, initialised SecurityroleprivilegeRecord
     */
    constructor(roleId: Long? = null, privilegeId: Long? = null): this() {
        this.roleId = roleId
        this.privilegeId = privilegeId
    }
}
