/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.SryResponseDetails

import java.time.OffsetDateTime

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class SryResponseDetailsRecord() : TableRecordImpl<SryResponseDetailsRecord>(SryResponseDetails.SRY_RESPONSE_DETAILS), Record10<String?, String?, String?, String?, Int?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?> {

    open var masterId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var id: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var updatedBy: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdBy: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var rating: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var questionId: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var answerId: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var updatedOn: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var createdOn: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var staleId: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row10<String?, String?, String?, String?, Int?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?> = super.fieldsRow() as Row10<String?, String?, String?, String?, Int?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?>
    override fun valuesRow(): Row10<String?, String?, String?, String?, Int?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?> = super.valuesRow() as Row10<String?, String?, String?, String?, Int?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?>
    override fun field1(): Field<String?> = SryResponseDetails.SRY_RESPONSE_DETAILS.MASTER_ID
    override fun field2(): Field<String?> = SryResponseDetails.SRY_RESPONSE_DETAILS.ID
    override fun field3(): Field<String?> = SryResponseDetails.SRY_RESPONSE_DETAILS.UPDATED_BY
    override fun field4(): Field<String?> = SryResponseDetails.SRY_RESPONSE_DETAILS.CREATED_BY
    override fun field5(): Field<Int?> = SryResponseDetails.SRY_RESPONSE_DETAILS.RATING
    override fun field6(): Field<String?> = SryResponseDetails.SRY_RESPONSE_DETAILS.QUESTION_ID
    override fun field7(): Field<String?> = SryResponseDetails.SRY_RESPONSE_DETAILS.ANSWER_ID
    override fun field8(): Field<OffsetDateTime?> = SryResponseDetails.SRY_RESPONSE_DETAILS.UPDATED_ON
    override fun field9(): Field<OffsetDateTime?> = SryResponseDetails.SRY_RESPONSE_DETAILS.CREATED_ON
    override fun field10(): Field<String?> = SryResponseDetails.SRY_RESPONSE_DETAILS.STALE_ID
    override fun component1(): String? = masterId
    override fun component2(): String? = id
    override fun component3(): String? = updatedBy
    override fun component4(): String? = createdBy
    override fun component5(): Int? = rating
    override fun component6(): String? = questionId
    override fun component7(): String? = answerId
    override fun component8(): OffsetDateTime? = updatedOn
    override fun component9(): OffsetDateTime? = createdOn
    override fun component10(): String? = staleId
    override fun value1(): String? = masterId
    override fun value2(): String? = id
    override fun value3(): String? = updatedBy
    override fun value4(): String? = createdBy
    override fun value5(): Int? = rating
    override fun value6(): String? = questionId
    override fun value7(): String? = answerId
    override fun value8(): OffsetDateTime? = updatedOn
    override fun value9(): OffsetDateTime? = createdOn
    override fun value10(): String? = staleId

    override fun value1(value: String?): SryResponseDetailsRecord {
        this.masterId = value
        return this
    }

    override fun value2(value: String?): SryResponseDetailsRecord {
        this.id = value
        return this
    }

    override fun value3(value: String?): SryResponseDetailsRecord {
        this.updatedBy = value
        return this
    }

    override fun value4(value: String?): SryResponseDetailsRecord {
        this.createdBy = value
        return this
    }

    override fun value5(value: Int?): SryResponseDetailsRecord {
        this.rating = value
        return this
    }

    override fun value6(value: String?): SryResponseDetailsRecord {
        this.questionId = value
        return this
    }

    override fun value7(value: String?): SryResponseDetailsRecord {
        this.answerId = value
        return this
    }

    override fun value8(value: OffsetDateTime?): SryResponseDetailsRecord {
        this.updatedOn = value
        return this
    }

    override fun value9(value: OffsetDateTime?): SryResponseDetailsRecord {
        this.createdOn = value
        return this
    }

    override fun value10(value: String?): SryResponseDetailsRecord {
        this.staleId = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: Int?, value6: String?, value7: String?, value8: OffsetDateTime?, value9: OffsetDateTime?, value10: String?): SryResponseDetailsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    /**
     * Create a detached, initialised SryResponseDetailsRecord
     */
    constructor(masterId: String? = null, id: String? = null, updatedBy: String? = null, createdBy: String? = null, rating: Int? = null, questionId: String? = null, answerId: String? = null, updatedOn: OffsetDateTime? = null, createdOn: OffsetDateTime? = null, staleId: String? = null): this() {
        this.masterId = masterId
        this.id = id
        this.updatedBy = updatedBy
        this.createdBy = createdBy
        this.rating = rating
        this.questionId = questionId
        this.answerId = answerId
        this.updatedOn = updatedOn
        this.createdOn = createdOn
        this.staleId = staleId
    }
}
