/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.tables.records


import com.squer.prorpel.jooq.tables.SryResponseMaster

import java.time.OffsetDateTime

import javax.annotation.processing.Generated

import org.jooq.Field
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class SryResponseMasterRecord() : TableRecordImpl<SryResponseMasterRecord>(SryResponseMaster.SRY_RESPONSE_MASTER), Record13<String?, String?, OffsetDateTime?, String?, Int?, Int?, String?, String?, String?, String?, Int?, OffsetDateTime?, OffsetDateTime?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var createdBy: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var surveyDate: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    open var surveyBy: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var yearMonth: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var surveyYear: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var staleId: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var surveyFor: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var updatedBy: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var surveyId: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var surveyMonth: Int?
        set(value): Unit = set(10, value)
        get(): Int? = get(10) as Int?

    open var updatedOn: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    open var createdOn: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<String?, String?, OffsetDateTime?, String?, Int?, Int?, String?, String?, String?, String?, Int?, OffsetDateTime?, OffsetDateTime?> = super.fieldsRow() as Row13<String?, String?, OffsetDateTime?, String?, Int?, Int?, String?, String?, String?, String?, Int?, OffsetDateTime?, OffsetDateTime?>
    override fun valuesRow(): Row13<String?, String?, OffsetDateTime?, String?, Int?, Int?, String?, String?, String?, String?, Int?, OffsetDateTime?, OffsetDateTime?> = super.valuesRow() as Row13<String?, String?, OffsetDateTime?, String?, Int?, Int?, String?, String?, String?, String?, Int?, OffsetDateTime?, OffsetDateTime?>
    override fun field1(): Field<String?> = SryResponseMaster.SRY_RESPONSE_MASTER.ID
    override fun field2(): Field<String?> = SryResponseMaster.SRY_RESPONSE_MASTER.CREATED_BY
    override fun field3(): Field<OffsetDateTime?> = SryResponseMaster.SRY_RESPONSE_MASTER.SURVEY_DATE
    override fun field4(): Field<String?> = SryResponseMaster.SRY_RESPONSE_MASTER.SURVEY_BY
    override fun field5(): Field<Int?> = SryResponseMaster.SRY_RESPONSE_MASTER.YEAR_MONTH
    override fun field6(): Field<Int?> = SryResponseMaster.SRY_RESPONSE_MASTER.SURVEY_YEAR
    override fun field7(): Field<String?> = SryResponseMaster.SRY_RESPONSE_MASTER.STALE_ID
    override fun field8(): Field<String?> = SryResponseMaster.SRY_RESPONSE_MASTER.SURVEY_FOR
    override fun field9(): Field<String?> = SryResponseMaster.SRY_RESPONSE_MASTER.UPDATED_BY
    override fun field10(): Field<String?> = SryResponseMaster.SRY_RESPONSE_MASTER.SURVEY_ID
    override fun field11(): Field<Int?> = SryResponseMaster.SRY_RESPONSE_MASTER.SURVEY_MONTH
    override fun field12(): Field<OffsetDateTime?> = SryResponseMaster.SRY_RESPONSE_MASTER.UPDATED_ON
    override fun field13(): Field<OffsetDateTime?> = SryResponseMaster.SRY_RESPONSE_MASTER.CREATED_ON
    override fun component1(): String? = id
    override fun component2(): String? = createdBy
    override fun component3(): OffsetDateTime? = surveyDate
    override fun component4(): String? = surveyBy
    override fun component5(): Int? = yearMonth
    override fun component6(): Int? = surveyYear
    override fun component7(): String? = staleId
    override fun component8(): String? = surveyFor
    override fun component9(): String? = updatedBy
    override fun component10(): String? = surveyId
    override fun component11(): Int? = surveyMonth
    override fun component12(): OffsetDateTime? = updatedOn
    override fun component13(): OffsetDateTime? = createdOn
    override fun value1(): String? = id
    override fun value2(): String? = createdBy
    override fun value3(): OffsetDateTime? = surveyDate
    override fun value4(): String? = surveyBy
    override fun value5(): Int? = yearMonth
    override fun value6(): Int? = surveyYear
    override fun value7(): String? = staleId
    override fun value8(): String? = surveyFor
    override fun value9(): String? = updatedBy
    override fun value10(): String? = surveyId
    override fun value11(): Int? = surveyMonth
    override fun value12(): OffsetDateTime? = updatedOn
    override fun value13(): OffsetDateTime? = createdOn

    override fun value1(value: String?): SryResponseMasterRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): SryResponseMasterRecord {
        this.createdBy = value
        return this
    }

    override fun value3(value: OffsetDateTime?): SryResponseMasterRecord {
        this.surveyDate = value
        return this
    }

    override fun value4(value: String?): SryResponseMasterRecord {
        this.surveyBy = value
        return this
    }

    override fun value5(value: Int?): SryResponseMasterRecord {
        this.yearMonth = value
        return this
    }

    override fun value6(value: Int?): SryResponseMasterRecord {
        this.surveyYear = value
        return this
    }

    override fun value7(value: String?): SryResponseMasterRecord {
        this.staleId = value
        return this
    }

    override fun value8(value: String?): SryResponseMasterRecord {
        this.surveyFor = value
        return this
    }

    override fun value9(value: String?): SryResponseMasterRecord {
        this.updatedBy = value
        return this
    }

    override fun value10(value: String?): SryResponseMasterRecord {
        this.surveyId = value
        return this
    }

    override fun value11(value: Int?): SryResponseMasterRecord {
        this.surveyMonth = value
        return this
    }

    override fun value12(value: OffsetDateTime?): SryResponseMasterRecord {
        this.updatedOn = value
        return this
    }

    override fun value13(value: OffsetDateTime?): SryResponseMasterRecord {
        this.createdOn = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: OffsetDateTime?, value4: String?, value5: Int?, value6: Int?, value7: String?, value8: String?, value9: String?, value10: String?, value11: Int?, value12: OffsetDateTime?, value13: OffsetDateTime?): SryResponseMasterRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised SryResponseMasterRecord
     */
    constructor(id: String? = null, createdBy: String? = null, surveyDate: OffsetDateTime? = null, surveyBy: String? = null, yearMonth: Int? = null, surveyYear: Int? = null, staleId: String? = null, surveyFor: String? = null, updatedBy: String? = null, surveyId: String? = null, surveyMonth: Int? = null, updatedOn: OffsetDateTime? = null, createdOn: OffsetDateTime? = null): this() {
        this.id = id
        this.createdBy = createdBy
        this.surveyDate = surveyDate
        this.surveyBy = surveyBy
        this.yearMonth = yearMonth
        this.surveyYear = surveyYear
        this.staleId = staleId
        this.surveyFor = surveyFor
        this.updatedBy = updatedBy
        this.surveyId = surveyId
        this.surveyMonth = surveyMonth
        this.updatedOn = updatedOn
        this.createdOn = createdOn
    }
}
