/*
 * This file is generated by jOOQ.
 */
package com.squer.prorpel.jooq.routines


import com.squer.prorpel.jooq.Public

import java.util.UUID

import javax.annotation.processing.Generated

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class GenRandomUuid : AbstractRoutine<UUID>("gen_random_uuid", Public.PUBLIC, SQLDataType.UUID) {
    companion object {

        /**
         * The parameter <code>public.gen_random_uuid.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<UUID?> = Internal.createParameter("RETURN_VALUE", SQLDataType.UUID, false, false)
    }

    init {
        returnParameter = RETURN_VALUE
    }
}
