export const EMPLOYEE_HIERARCHY_START = 'EMPLOYEE_HIERARCHY_START'
export const EMPLOYEE_HIERARCHY_SUCCESS = 'EMPLOYEE_HIERARCHY_SUCCESS'
export const EMPLOYEE_HIERARCHY_FAIL = 'EMPLOYEE_HIERARCHY_FAIL'
