export const GET_SELECT_DROPDOWN_START = 'GET_SELECT_DROPDOWN_START'
export const GET_SELECT_DROPDOWN_SUCCESS = 'GET_SELECT_DROPDOWN_SUCCESS'
export const GET_SELECT_DROPDOWN_FAIL = 'GET_SELECT_DROPDOWN_FAIL'