export const GET_LOV_START = 'GET_LOV_START'
export const GET_LOV_SUCCESS = 'GET_LOV_SUCCESS'
export const GET_LOV_FAIL = 'GET_LOV_FAIL'

export const COMMON_SELECT_START = 'COMMON_SELECT_START'
export const COMMON_SELECT_SUCCESS = 'COMMON_SELECT_SUCCESS'
