export const UI_MENU_START_ACTION = 'UI_MENU_START_ACTION'
export const UI_MENU_SUCCESS_ACTION = 'UI_MENU_SUCCESS_ACTION'
export const UI_MENU_FAIL_ACTION = 'UI_MENU_FAIL_ACTION'

export const UI_SET_PAGE_TITLE = 'UI_SET_PAGE_TITLE'
