export const GET_FORM_META_START = 'GET_FORM_META_START'
export const GET_FORM_META_SUCCESS = 'GET_FORM_META_SUCCESS'

export const COMMON_SEARCH_META_START = 'COMMON_SEARCH_META_START'
export const COMMON_SEARCH_META_SUCCESS = 'COMMON_SEARCH_META_SUCCESS'

export const COMMON_SEARCH_START = 'COMMON_SEARCH_START'
export const COMMON_SEARCH_SUCCESS = 'COMMON_SEARCH_SUCCESS'

export const COMMON_UPDATE_INIT_START = 'COMMON_UPDATE_INIT_START'
export const COMMON_UPDATE_INIT_SUCCESS = 'COMMON_UPDATE_INIT_SUCCESS'

export const COMMON_SEARCH_RESET_START = 'COMMON_SEARCH_RESET_START'

export const COMMON_SAVE_META_START = 'COMMON_SAVE_META_START'
export const COMMON_SAVE_META_SUCCESS = 'COMMON_SAVE_META_SUCCESS'

export const COMMON_NEW_META_START = 'COMMON_NEW_META_START'
export const COMMON_NEW_META_SUCCESS = 'COMMON_NEW_META_SUCCESS'